### ISSUE TITLE
Can't open files with filenames not in English

### ISSUE THREAD

**Issue by zetaisgood** [easymodo/qimgv#102]
Trying to open files titled in languages other than English produces a message "File does not exist or is not supported".

**Comment by easymodo** [comment]
Can't reproduce.

What is the file name? Or even better, upload that file somewhere

**Comment by zetaisgood** [comment]
It happens when I try to open these files from Explorer.
Here's an image with Russian filename: https://drive.google.com/file/d/1t8rU4rM2CO49HnIcgU6jZ2NEhSPt7ATM/view

**Comment by easymodo** [comment]
does this still happen with 0.8.4?

**Comment by easymodo** [comment]
i'm assuming this works now
