### ISSUE TITLE
The EXIF info windows is empty

### ISSUE THREAD

**Issue by Giova84** [easymodo/qimgv#105]
When I was using the previous version 0.7.3 I had a script to read exif info of the images:

```
#!/bin/bash

currimage="$1"
readexifdata=$(exiftool "$currimage")
printf "$readexifdata" > /tmp/exifinfo

zenity --text-info --ok-label="OK" --cancel-label=Quit --width=800 --height=400 --filename=/tmp/exifinfo --font=DroidSansMono,10
```
I laaunch this script by using the "E" key in qimgv

Which results in:
https://i.ibb.co/551zY01/Full-Exif-Info.png

Now, with 0.8.1, if I use the built-inf exif reader (by using the "I" key) such exif info window is empty:
https://i.ibb.co/kDSkTRt/Empty-Exif-Info.png

**Comment by easymodo** [comment]
But that's not *exif* tags, just general info about file. I could include it in that panel i guess

**Comment by Giova84** [comment]
Ok, so is due to the fact that my script which is using `exiftool`, read everything info of the image, also the info which are displayed by the new feature which you implemented, Feel free to close this ticket.

**Comment by easymodo** [comment]
Well i can turn that exif panel into a general image info kinda thing. I'll keep that in mind.

**Comment by githlp** [comment]
> But that's not _exif_ tags, just general info about file. Here's what it shows currently https://i.imgur.com/yL5GlDK.jpg

Is that ImageInfo/ExifInfo window configurable ?

I have no Date/Time Info in my Info-toggle but it might be that i configured that out - if that was ever possible.

I use 1.0.2 on arch.

**Comment by githlp** [comment]
ok, i checked with
`identify -verbose image1.jpg`

    date:create: 2019-03-02T11:25:18+00:00
    date:modify: 2018-05-09T18:15:08+00:00
    date:timestamp: 2022-12-13T15:19:54+00:00
    ...
    exif:DateTime: 2018:05:09 18:15:08
    exif:DateTimeDigitized: 2018:05:09 18:15:08
    exif:DateTimeOriginal: 2018:05:09 18:15:08

`identify -verbose image2.jpg`

    date:create: 2015-05-30T18:16:12+00:00
    date:modify: 2015-05-25T15:47:24+00:00
    date:timestamp: 2022-12-13T15:21:59+00:00
    ...
    exif:DateTime: 2015:05:25 17:47:06
    exif:DateTimeDigitized: 2015:05:08 16:47:26
    exif:DateTimeOriginal: 2015:05:08 16:47:26


The image1.jpg has Date/Time in the ImageInfo-Toggle, the second one not..

So which Exif-Info from the picture is used ?
