### ISSUE TITLE
Copy file to  clipboard does nothing

### ISSUE THREAD

**Issue by Giova84** [easymodo/qimgv#106]
If i open an image and then i copy it to the clipboard by using "CTRL+C", an infobar tells me  "File copied", but is not copied into the clipboard:  I cannot copy the file itself in another location/folder as i cannot copy the image itself, eg inside an image editor.

**Comment by easymodo** [comment]
Weird, i can copy & paste into filemanager / chat client etc. But pasting into gimp indeed does not work.

**Comment by Giova84** [comment]
BTW i'm using Linux (manjaro).
I have done this test:
if i copy the image path and i paste it in a text editor i get:
/home/user/Pictures/wallpapers/ws_Black_&_Green_Carbon_1366x768.jpg
If i copy the image to the clipboard and i paste it in a text editor i get:
file:///home/user/Pictures/wallpapers/ws_Black_&_Green_Carbon_1366x768.jpg
But still not work, maybe because on linux behaves differently.

**Comment by easymodo** [comment]
i'm on kde and it works. what de do you use? xfce?

**Comment by Giova84** [comment]
Yes, I'm on xfce

**Comment by WXZhao7** [comment]
Now, I still can't copy picture in xfce:(
