### ISSUE TITLE
no menu under right click

### ISSUE THREAD

**Issue by alekksander** [easymodo/qimgv#107]
as title says – RMB is ignored
this is 8.1

**Comment by easymodo** [comment]
Can you check if it is assigned in settings? action is "contextMenu"

**Comment by alekksander** [comment]
it's available to add, but it had to disappear on update from 7.3 to 8.1. i cannot find option to view exif. is support for exif added with newest version yet?

**Comment by easymodo** [comment]
There's a panel with exif info, you can access it via `I` (or bind `toggleImageInfo` to any key)

**Comment by Richard-L** [comment]
@easymodo this issue has been re-introduced with v0.9alpha1 sadly.

**Comment by easymodo** [comment]
wait are you sure? is it bound in settings? working fine over here

**Comment by easymodo** [comment]
if you hold RMB and move a few pixels before releasing it is treated as zoom, maybe you did that

**Comment by Richard-L** [comment]
Sorry my bad. Thought something else was made that was suggested as I composed another issue. I shall after all do that now. Please ignore my comment in here.
