### ISSUE TITLE
Cannot open files with custom file extension since updating to 0.8.2

### ISSUE THREAD

**Issue by Kattus** [easymodo/qimgv#108]
I often deal with files that have an extension of `.jpg.1` and so on, due to duplicates and how wget deals with that. I updated qimgv today to the -git package from AUR, and I can no longer open these files.

Expected behaviour (0.7.3):
![](https://too.lewd.se/91340ce4fc32_qimgv_2019-08-28_23-58-17.png)

Actual behaviour (0.8.2):
![](https://too.lewd.se/bde82db69c2b_qimgv_2019-08-29_00-01-00.png)

`qimgv-git v0.8.2.r0.g695d3e0-1`

**Comment by easymodo** [comment]
Done. Note that it won't show _other files_ with the wrong extension, only the one you opened. (checking entire directory's mime-type is slow)

**Comment by Kattus** [comment]
Yeah that's expected (and how it worked before), thanks.
