### ISSUE TITLE
No longer showing filesize in title since 0.8.2

### ISSUE THREAD

**Issue by Kattus** [easymodo/qimgv#109]
before: ![](https://too.lewd.se/4cda33c08828_2019-08-29_01-09-23.png)
after: ![](https://too.lewd.se/6b0de4665b71_2019-08-29_01-10-47.png)

while I'm at it, can this display a decimal or two? at least when at these small values

**Comment by Kattus** [comment]
Closing this since it's been fixed in the current version.

**Comment by easymodo** [comment]
Now it also properly formats filesize
