### ISSUE TITLE
Add ability to use drag & drop 

### ISSUE THREAD

**Issue by nick-s-b** [easymodo/qimgv#110]
Hi!
One thing that I've always missed from other viewers is the ability to drag an image and drop it onto a file upload box or just drop it onto a desktop (it would usually make a copy).

Here's a use case... say you're browsing a folder with hundreds of images with `qimgv` and you find an image that you want to do something with. What now? You can't "reveal it in FM". You can't drag it onto GIMP/Kirta or Firefox upload box. Your course of action is to note the filename and then search for it with your FM of choice. Wouldn't it be better to have an ability to just drag an image from within `qimgv`? To see what I mean, just try `xviewer` or `eog` or something  like that and drag an image into Github's comment file upload region.

Thanks for reading :)

**Comment by easymodo** [comment]
Hi

Pretty neat feature indeed. Done.

Tested with qt / gtk filemanagers, gimp etc. Seems to work.

_(number of xorg crashes during testing: `4`)_

**Comment by nick-s-b** [comment]
Amazing! Thank you so much!

**Comment by nick-s-b** [comment]
Quick update... been using it for 2 hrs or so and I've experienced no crashes of any kind. All the things you'd expect with D&D work well... stuff like Shift or Alt dragging too! 
Fantastic!
