### ISSUE TITLE
UI improvements suggestions

### ISSUE THREAD

**Issue by alekksander** [easymodo/qimgv#113]
Hello. I have few suggestions regarding UI that @easymodo You might consider important to work on.

**1.** re-arrange order this buttons:
![Screenshot_20190908_134632](https://user-images.githubusercontent.com/3148302/64487784-2199a200-d23f-11e9-84a0-ee766520728f.png)
to be more intuitive – in my understanding it should look like this (mockup):
![Screenshot_20190908_134632(2)](https://user-images.githubusercontent.com/3148302/64487806-5c033f00-d23f-11e9-853a-2be848a0d95a.png)
so the viewing related button is first and isolated from settings/close

**2.** stick scrollbar to the edge of the screen so it can be selected faster without precision – and so it is the way it works in most fullscreen applications (attached pic shows that pointer is not hovering it)
![Screenshot_20190908_135140](https://user-images.githubusercontent.com/3148302/64487842-eea3de00-d23f-11e9-827f-9b84f444f2ed.png)

**3.** probably most important one – i cannot use pointer to use video controls on fullscreen – lower bar with photo selection pop-ups too soon
https://streamable.com/2jkhv

thank You

**Comment by easymodo** [comment]
Can't do much else except moving video controls at the top. If you have better ideas let me know..
Placing it just above panel just looks wrong.

**Comment by Hrxn** [comment]
+1 to re-arranging the order of the menu bar buttons.

**Comment by easymodo** [comment]
done

**Comment by alekksander** [comment]
How about more transparency plus default single click?

**Comment by easymodo** [comment]
elaborate
