### ISSUE TITLE
Action for Scaling algorithm?

### ISSUE THREAD

**Issue by f3l-x** [easymodo/qimgv#114]
Is it possible to get an action for the scaling algorithm (bilinear, nearest neighbor) so it could be assigned to a key and changed within the GUI without calling the options dialog?
This is something i am really used to from other viewers (sxiv, feh) and i miss it so much. 
Thank you and very good work.

**Comment by easymodo** [comment]
I could do that, yes

**Comment by f3l-x** [comment]
Works!
