### ISSUE TITLE
Can't run 0.8.4 version (Win, x64, 7z)

### ISSUE THREAD

**Issue by eddiezato** [easymodo/qimgv#117]
![Untitled](https://user-images.githubusercontent.com/11173476/65382051-a7314d80-dd27-11e9-85f0-6e0c88008636.png)

**Comment by AeliusSaionji** [comment]
Can confirm. The 32bit build also fails to run on Win10 x64

![image](https://user-images.githubusercontent.com/4342746/65382517-411bda80-dcd5-11e9-8674-5bffb6aba722.png)

**Comment by easymodo** [comment]
my bad, reuploaded
