### ISSUE TITLE
Add 'overlay info' color setting

### ISSUE THREAD

**Issue by ongots** [easymodo/qimgv#119]
Хочу сделать так
![2019-09-22_103019](https://user-images.githubusercontent.com/43604031/65384597-54a26200-dd24-11e9-8d2b-3dd5dcfec872.png)

**Comment by ongots** [comment]
И добавьте кнопку свернуть окно, хотя бы опционально.

**Comment by easymodo** [comment]
![image](https://user-images.githubusercontent.com/5484275/68393953-a9375a80-0175-11ea-9564-3f507d7f67f4.png)

![image](https://user-images.githubusercontent.com/5484275/68393996-b9e7d080-0175-11ea-8c71-0757171d4d01.png)

**Comment by easymodo** [comment]
будет в v0.8.7

**Comment by ongots** [comment]
Добавьте опцию "Info bar background", чтобы отключить фон
