### ISSUE TITLE
[MP4] some mp4 files do not play and dont generate thumbnails

### ISSUE THREAD

**Issue by 1sad** [easymodo/qimgv#121]
some mp4 files do not play and dont generate thumbnails
files are perfectly openable by other players and the bundled mpv.exe 
while in gallery view when you get to the file several instances of mpv.exe open up in the task manager and promptly close

**Comment by easymodo** [comment]
Those mpv.exe instances is thumbnail generator doing it's thing.

Could you upload an mp4 that does not play? I'll test it over here

**Comment by 1sad** [comment]
[Desktop.zip](https://github.com/easymodo/qimgv/files/3673376/Desktop.zip)
![thumbs](https://user-images.githubusercontent.com/23120024/65915969-29330d80-e3dd-11e9-8a4b-1b5e2997159b.PNG)

had the same problem on a different machine, though the files were different, but also mp4

**Comment by easymodo** [comment]
alright fixed, i'll make a windows build tomorrow

thanks for reporting

**Comment by 1sad** [comment]
h-hayai! thanks!

**Comment by easymodo** [comment]
here ya go fam [v0.8.5](https://github.com/easymodo/qimgv/releases/tag/v0.8.5)

**Comment by 1sad** [comment]
niiiicee
