### ISSUE TITLE
Confirm upon delete

### ISSUE THREAD

**Issue by Vig2OOO** [easymodo/qimgv#122]
Please add a delete confirmation dialog before deleting an image so images aren't accidentally deleted.

**Comment by AlekzNet** [comment]
Yep, I vote for this one too! Just hit "Delete"  instead of "Backspace" (fortunately I have a backup).

**Comment by easymodo** [comment]
Okay, i've finally remembered about this issue. Done.
__Settings > Advanced__ page (confirmations are on by default)
