### ISSUE TITLE
Webp opened but not shown

### ISSUE THREAD

**Issue by Ser-Gen** [easymodo/qimgv#124]
Windows 10
0.8.6 x64

When I directly open attached image, Qimgv window opens but shows nothing.
When I switch to webp from another image, it shows successfully.

[mbike.webp.zip](https://github.com/easymodo/qimgv/files/3732733/mbike.webp.zip)
*zip because github doesn't supports webp upload*

**Comment by easymodo** [comment]
Can't reproduce this one..  I _could_ be some encoding issue.. do you have cyrillic in filepath? Other files open fine from the same directory right?

**Comment by Ser-Gen** [comment]
No, filepath is ascii only.
Right, png, gif, jpeg opens fine from same directory.

I place image in `C:\mbike.webp`. It's single image in this foder. Same issue.
When I put openable png next to this image, webp opens by switch from png.

**Comment by po5** [comment]
Experiencing this as well.

**Comment by linsui** [comment]
I can reproduce this problem. Other webp image can't be showed for me, either.

**Comment by easymodo** [comment]
can someone please test on the [dev build](https://github.com/easymodo/qimgv/releases/tag/v0.8.6.99)?

**Comment by linsui** [comment]
It works well for me. :+1:

**Comment by Ser-Gen** [comment]
Works for me as well.

**Comment by easymodo** [comment]
thanks
