### ISSUE TITLE
Lost focus after renaming files? Unable to move files

### ISSUE THREAD

**Issue by nick-s-b** [easymodo/qimgv#129]
**version: 0.8.6 (latest AUR update; Qt: 5.13.1**

Hi,

I've noticed this bug a bunch of times when I'm moving images around. It's pretty annoying at times.

Steps to reproduce (I'm assuming standard key mapping below so just substitute them with customized ones):

1) press `m` to show the "Move to" panel
2) press `F2` to rename a file; Press Enter
3) try to move a file by pressing number keys and you won't be able to

Expected behavior: you should be able to move files to various folders after a file rename since the  "Move to" panel is still visible.

Temp fix is to press `m` twice to hide/show move panel again. But that slows down the workflow.

Thanks!

**Comment by easymodo** [comment]
thanks for reporting, fixed on dev branch

**Comment by nick-s-b** [comment]
Hi, thanks so much for looking into this. I just gave the dev branch a try and when I rename a file, I get "Source file is not writable" message. The filename displayed in the qimgv's title is the old name but the file name has changed on the disk. Moving also doesn't work because the old filename is still the 'active' one.

**Comment by easymodo** [comment]
my bad, i broke it in previous commit

**Comment by nick-s-b** [comment]
It works perfectly now! Thank you!

**Comment by nick-s-b** [comment]
Hi, I just came across another bug that's related to this so I don't want to open another issue. 

If you have the Move panel open and you also have some mp4/webm movies in the same folder and you browse through them, move will stop working after viewing a video. You have to manually disable/enable Move panel after the video for the Move panel to be active again.

**Comment by easymodo** [comment]
Hi
So i've poked this around some more, and i think it finally works correctly now. _Proobably_
