### ISSUE TITLE
Crash and coredump when renaming a file

### ISSUE THREAD

**Issue by nick-s-b** [easymodo/qimgv#130]
Hi,
I've noticed that `qimgv` crashes with a coredump when renaming a file.

Steps to reproduce:

1) Open image
2) Press F2 to rename
3) Press left arrow key
4) Press Enter

`qimgv` will now crash with this error message:

````
$ qimgv
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot get file time: No such file or directory [/home/user/Pictures/image1.png__tmp]
[1]    187874 abort (core dumped)  qimgv
````

I can reproduce this 100% of the time.

**Comment by easymodo** [comment]
fixed
