### ISSUE TITLE
Cache gets filled up with PNG thumbnails of videos, disabling cache does nothing

### ISSUE THREAD

**Issue by 1sad** [easymodo/qimgv#131]
Cache folder gets filled up with full-res .PNG thumbnails of video files, has quite a dramatic effect on folder size after opening video files. Disabling thumbnail cache only disables the thumbnails generated for image files, not video files. And video thumbnails are full size .PNG regardless of the setting.

Would be nice to have them be disabled by the setting, and also when enabled have them be the same small format as image thumbnails instead of huge png files.

**Comment by easymodo** [comment]
weird, they should be autoremoved on program exit. maybe i broke something

**Comment by 1sad** [comment]
still, even if they were, that can take real large amounts of space if you have big video folders :pray:

**Comment by easymodo** [comment]
fixed in the next release

**Comment by 1sad** [comment]
nice thanks 👍
