### ISSUE TITLE
When will the installer be available?

### ISSUE THREAD

**Issue by mrkaban** [easymodo/qimgv#133]
When will the installer format release be available? 7z format is also not convenient, since not all users have enough knowledge to open it, it is better to zip.

I ask you, please collect the installer, it's not difficult, programs like Inno Setup can do this without much difficulty.

The program has been added to my website with approximately 1300 people daily traffic ([link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%B0/%D0%BF%D1%80%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80/qimgv-%D0%BF%D1%80%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80-%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B9.html)).

**Comment by easymodo** [comment]
>7z format is also not convenient, since not all users have enough knowledge to open it, it is better to zip.
Looks like it is windows that is not convenient, seeing as it still can't open 7z in 2019. But sure i'll zip from now on

I won't do an installers for every small/not significant release, it is a pain in the ass. But 0.8.7 will have them

**Comment by mrkaban** [comment]
So no one will download the intermediate versions, this is the same pain for users, only in your case it is one, and in the case of users this is multiplied by their number.

**Comment by s-r-grass** [comment]
It’s immediately obvious that the developer cares about users. The developer does not give a damn about the user. For those who do not understand, this is sarcasm (ironic humor).

**Comment by easymodo** [comment]
alright, alright, point taken

**Comment by AeliusSaionji** [comment]
I hate to nitpick about the installer- I know too well that it is a pain and I don't want to pile on here.

But the x64 version is installing to Progfiles x86. Is that intentional?

**Comment by easymodo** [comment]
Yes, if you had it installed there previously. I'll look into fixing that later

Also wait a little bit, i'm re-doing builds with a crash fix

**Comment by AeliusSaionji** [comment]
I uninstalled and reinstalled, it went to the correct programfiles. Thanks!

**Comment by mrkaban** [comment]
Thank you very much for the installers!
