### ISSUE TITLE
[Feature Request] Volume slider and mute/unmute button on video OSD controls, or binds

### ISSUE THREAD

**Issue by 1sad** [easymodo/qimgv#135]
Would be really nice to have a volume slider or volume up/down binds available. 
The "mute videos" setting could work as initial mute, and then you would increase volume from 0% to whatever you like with the slider or binds (personally i use the scrollwheel in mpc for doing that, everything initially starts muted, its very comfortable to use in my opinion, and solves the problem of having media with varying volumes or unwanted sound).

**Comment by easymodo** [comment]
Yeah this shouldn't be a problem to implement.

**Comment by easymodo** [comment]
done except for volume slider, i'll do it sometime later (but shortcuts are already available)

**Comment by 1sad** [comment]
Fantastic, thank you!
If I could add another request for the future, if it could be possible to have keybinds not conflicting i.e. when images are on screen I zoom in with mouse wheel, but when videos are on screen, zoom doesn't work, so I control volume with mouse wheel.
Currently it doesn't let you bind different commands to the same key.

Again thank you!
