### ISSUE TITLE
Support colon, semicolon for keybind

### ISSUE THREAD

**Issue by AeliusSaionji** [easymodo/qimgv#144]
In trying to map vim-like bindings for scrolling, I discovered that `;` is not accepted. Probably a number of other keys, too. Mind adding support for those? Can I manually add it if I were to edit the config file?

Thanks.

**Comment by easymodo** [comment]
>Can I manually add it if I were to edit the config file?

Nope. 

I'll rework key handling for v0.8.9.

**Comment by easymodo** [comment]
done
