### ISSUE TITLE
qimgv stopped playing MP4 files... shows black screen

### ISSUE THREAD

**Issue by nick-s-b** [easymodo/qimgv#145]
Hi,
I've noticed that very recently, `qimgv` has stopped playing mp4 files. All you see now is the black screen when `qimgv` encounters an mp4 file when browsing through a folder.

OS: Linux 5.4.3
qimgv: 0.8.8 (latest github stable branch)
mpv: 0.30.0-302-g2dbe33ce83

**Comment by easymodo** [comment]
Weird, just grabbed latest `mpv-git` and it works. Does it output anything to console when you try playing a file?

Just in case check that you have this file

`/usr/lib/libqimgv_player_mpv.so`

`/usr/lib/libqimgv_player_mpv.so.1`

`/usr/lib/libqimgv_player_mpv.so.1.0`

**Comment by nick-s-b** [comment]
Freshly compiled mpv:
````
$ mpv --version
mpv 0.30.0-374-g05fb6f906d Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sat Dec 21 02:51:45 EST 2019
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2.1
````

qimgv:
````
qimgv 0.8.8 - A fast and configurable image viewer. Written in qt5.
...
Enabled build options:
    "USE_MPV"

````

Other stuff:
````
$ ls -l /usr/lib/libqimgv_player_mpv.so /usr/lib/libqimgv_player_mpv.so.1 /usr/lib/libqimgv_player_mpv.so.1.0
lrwxrwxrwx 1 root root    24 Dec 15 05:32 /usr/lib/libqimgv_player_mpv.so -> libqimgv_player_mpv.so.1
lrwxrwxrwx 1 root root    26 Dec 15 05:32 /usr/lib/libqimgv_player_mpv.so.1 -> libqimgv_player_mpv.so.1.0
-rwxr-xr-x 1 root root 96088 Dec 15 05:32 /usr/lib/libqimgv_player_mpv.so.1.0
````

However, when I try:
````
$  qimgv '/tmp/test.mp4'
QImage::scaled: Image is a null image
````

test.mp4 is attached. Plays fine in vlc, mpv etc.

[test.mp4.zip](https://github.com/easymodo/qimgv/files/3991191/test.mp4.zip)

**Comment by easymodo** [comment]
yep this one doen't play. looking into it

**Comment by easymodo** [comment]
Alright i've removed a mimetype check, now it will try playing `.mp4` / `.webm` regardless of contents 

you can grab a dev branch, fix is there

**Comment by easymodo** [comment]
BTW if you are on arch the easy way is just editing pkgbuild from aur before install

![image](https://user-images.githubusercontent.com/5484275/71305365-81c1e780-23db-11ea-8797-f3803a5ec2f2.png)

**Comment by nick-s-b** [comment]
Compiled it and it works perfectly as before. Yeah, I had that branch in the pkgbuild before but forgot to edit it after a recent update... thanks so much!!!
