### ISSUE TITLE
Show in directory

### ISSUE THREAD

**Issue by darsain** [easymodo/qimgv#146]
Current context menu option "Show directory" will open the directory of currently viewed file, but way more useful would be to rename it to "Show in directory", and also focus/select the current file in that directory. Really miss this feature from other image viewers.

**Comment by easymodo** [comment]
done

**Comment by rieje** [comment]
Do you mean it is supposed to open a file manager application and highlight/select the image? Is this dependent on whether the file manager supports this? When I "Show in folder", it just opens the directory of the file without highlighting/selecting the file.

I'm on the active branch.

**Comment by easymodo** [comment]
yes it depends on fm
currently it works on: 
windows
mac
dolphin
nautilus

i couldnt find how to open thunar from terminal with a file pre-selected. if there is a way - let me know
