### ISSUE TITLE
Thumbnail panel hover is finicky 

### ISSUE THREAD

**Issue by darsain** [easymodo/qimgv#147]
Thumbnail panel shows when I mouse over it from the bottom, but not from the top (when starting on the app title, or outside the app window). It would be better if mouse position would consistently dictate the visibility of the thumbnail bar. As it is, it feels janky to use, as if it's lagging, or failed to register mouse events and I have to re-hover.

To illustrate:

![New Project](https://user-images.githubusercontent.com/538801/71308591-ce6aea00-23fe-11ea-8c02-0428811103a8.png)

If this is a design decision, and on purpose, I'd argue against it since it creates an inconsistent UI behavior when sometimes when your mouse is on this position it's a thumbnail bar, and sometimes it's an image, so you can't reliably predict your action and always have to pay attention to which of these 2 states is true before you can control the app.

**Comment by easymodo** [comment]
Yeah it's on purpose ( to avoid panel unintentionally popping up when you are just moving cursor over the window ). But i see your point, someone really could think it's just buggy

**Comment by easymodo** [comment]
Ok now I remember the real reason why i did that. It gets in the way when you move the image and the cursor ends up in the panel area. [Click.](https://streamable.com/a904r)

**Comment by darsain** [comment]
Wouldn't it be trivial to not show it when dragging? I'd consider it a pretty expected behavior in such a case.

**Comment by easymodo** [comment]
done
