### ISSUE TITLE
Controlling the video controls visibility

### ISSUE THREAD

**Issue by darsain** [easymodo/qimgv#148]
I never liked the UX of controls popping in whenever I bump the mouse a little, or disappearing when I want to interact with them but I sit idle for a bit. On top of it, there is a bug where they don't auto-hide when I mouse out of the app window, and just stay there visible forever.

If I could suggest: lets completely drop the auto-hiding here, and implement show on proximity, where they would only get visible when mouse is near them, with an opacity ramp up that starts at 0 around 100-200px away from them, and gets to 1 at 50px proximity.

This would give us complete control over when and how much they are visible, creating predictable and consistent UX.

---

And sorry for the slight issue spam 😳, but I wanted a simple media viewer just like this for SO LONG, and when I found this just now it got me so exited that I got invested and want to make it perfect :) Great job!

**Comment by easymodo** [comment]
>And sorry for the slight issue spam

Absolutely no problem! UX is important
