### ISSUE TITLE
Remember un-maximazed window size and position between sessions

### ISSUE THREAD

**Issue by darsain** [easymodo/qimgv#150]
The un-maximazed window size and position is never remembered between sessions, so when the app is closed and than re-started in maximized state, the maximize button does nothing to the size and position of the window.

To replicate:
1. Resize the app window down and position it somewhere.
1. Maximize the window.
1. Close the app = the size and position from 1. is forgotten.
1. Reopen the app.
1. Click maximize button a couple times = does nothing.

**Comment by easymodo** [comment]
done 
https://github.com/easymodo/qimgv/releases/tag/v0.9-alpha1
