### ISSUE TITLE
Zooming and view mode tweaks

### ISSUE THREAD

**Issue by darsain** [easymodo/qimgv#153]
### Option for automatic zoom limit

**Expand smaller images** is an awesome feature to automatically zoom in smaller images, but it always zooms to fill the whole screen space, which is not that useful for tiny images that have only a couple hundred or less pixels, in which case you just see a big blur.

To fix this, I'd love for the **Expand smaller images** feature to be accompanied by a 2nd **Expand limit** option to control the zoom limit. If I set it to lets say 2x, the image won't be upscaled to more than 2x the size of the original dimensions.

### Indicator

Whenever the image is not displayed in the original dimensions, there should be a small indicator in some of the bottom corners with percentage value of the current view compared to the original. Don't just add it to the image info bar - I have that turned off since I'm not interested in it and I want more screen space, but I want to see the scaling data.

This indicator should disappear when the image is displayed in its original size so people have the whole screen space available when they are want to see the original 1:1 view. This would also make it not suitable for info bar.

### Remove manual zoom limit

When zooming manually, there is an arbitrary limit on how much you can zoom. Dunno why? Please remove. Or at least ignore it until the image doesn't fill at least the whole screen space.

For example, I have a small 48x48 image that I can zoom only to fill like 20% of the screen space and than it stops me from zooming more. This even destroys the current viewing flow where I have Expand smaller images enabled, I open the 48x48 image, it is stretched to fill the whole screen space, than I want to adjust the zoom by right click dragging, and instead of seamlessly adjusting the current zoom, it snaps down to the manual zoom limit and won't allow me to go higher.

### Clear toggleFitMode when navigating

Currently, when I execute toggleFitMode, it properly toggles between **1:1** and currently configured viewing type, but it also carries over when navigating to the next/prev image. This shouldn't happen.

Reasoning/design:

**Image view options** (including Expand smaller images) are global options that control how I want to see the images when navigating by default. Carries over sessions but gets overwritten by below.

***right click context menu view buttons*** are a per session viewing type adjustments. This should get cleared when user restarts the app. Overwritten by below.

**toggleFitMode** (and related key bindable functions if there are some) is a temporary feature that controls how I want to see currently viewed image. This should get cleared when I navigate to next/prev image.

**Comment by easymodo** [comment]
>expand smaller images feature to be accompanied by a 2nd Expand limit option to control the zoom limit

This is the one of those things i didn't know i needed. So much better.

**Comment by easymodo** [comment]
So, most of the stuff is in v0.8.9

Except zoom level indicator.. Still thinking where to put it so it won't overlap with other stuff

**Comment by darsain** [comment]
> So, most of the stuff is in v0.8.9

Awesome! :)

> Still thinking where to put it so it won't overlap with other stuff

No reason to over-complicate it, just a discrete little box in bottom left:

![image](https://user-images.githubusercontent.com/538801/74191357-bcb20000-4c53-11ea-937c-731a0dcd05df.png)

But don't forget to hide it when viewing in 1:1.

**Comment by easymodo** [comment]
this will be in the next build

![screenshot 13](https://user-images.githubusercontent.com/5484275/75376837-668ebf00-58d9-11ea-9396-5cc9f45143ed.jpg)

**Comment by darsain** [comment]
Looks great 👍

**Comment by Richard-L** [comment]
Where do I turn this on now that it's been implemented?

**Comment by easymodo** [comment]
general > zoom indicator. 
but it think the way it auhotides right now looks kinda crappy.
