### ISSUE TITLE
Zoom in/out doesn't work if plasma mouse gestures are set to RMB

### ISSUE THREAD

**Issue by alekksander** [easymodo/qimgv#155]
to be honest i'm not sure if it's something to report.  RMB hold and move up/down is great way to control zoom of images, but it collides with plasma gestures (if also set to RMB) — making it impossible to use. i know there are plenty of options which include excluding gestures for specific applications, yet i decided to inform You (@easymodo) that this takes place, and perhaps it's wise in this situation to let user control which button to hold for zoom, just as other keys are controllable. thanks!

**Comment by easymodo** [comment]
good to know, thanks

**Comment by alekksander** [comment]
this one got worse. i'm unable to use zoom despite plasma is set not to use any gestures in qimgv. i'll report to bugs.kde.org

**Comment by easymodo** [comment]
how did you set it to ignore qimgv?

honestly i can't even find an option. i know you can disable global shortcuts but not sure about khotkeys

**Comment by easymodo** [comment]
>perhaps it's wise in this situation to let user control which button to hold for zoom

I don't want to change how basic mouse interaction works in qimgv (clicks etc). The code will just turn into a mess. 
Also what would you change it to? Using side mouse buttons would be uncomfortable, as well as mouse wheel (I've thought about changing zoom to wheel, even tried using it for a month, but it just felt too clunky

**Comment by alekksander** [comment]
it's not so obvious, i have to admit it, but the whole gesture idea got to me profoundly, so i had to dig it ;) they are improving plasma quite intensively lately, so perhaps there is a chance they will rewrite this one too
![Screenshot_20200517_225054](https://user-images.githubusercontent.com/3148302/82159748-e3a25280-9890-11ea-9005-c366bce6bc57.png)


about the zoom button i also think current solution is best way to do it. before i found Your app i was using one with wheel as zoom, and ←LMB RMB→, but that wasn't working well ever after months of practice. in my first comment i suggested to give user option how to zoom and that still might be a good option, but to hardcode walkaround for a kde bug is probably not the way to go. folks at kde has to fix this one at some point. i will post a link to bug report once i ask devs at irc and actually report it.

**Comment by alekksander** [comment]
wait… do You notice how i have 4 gestures not grouped? i just tried grouping them and writing same exclude rule for them just to try… and i didn't even had to. only grouped them without any rules and viola! plasma is not blocking RMB any more, and zooming works again :)

**Comment by easymodo** [comment]
Well that's an _interesting_ UX decision from kde devs :smirk:
