### ISSUE TITLE
zoom with rmb+scroll

### ISSUE THREAD

**Issue by roger21** [easymodo/qimgv#157]
hey,

so it would be nice to be able to zoom/unzoom with rmb+scroll (i tried setting it up in the shortcuts but it doesn't seems to be possible)

and also the zoom with rmb+mouse up is quite really a very bad idea, if you want to zoom something in the top tier of the image ... well it is more than painful ... you zoom a little then you have to move the picture then you zoom a little more .... really painful

**Comment by easymodo** [comment]
noted

**Comment by easymodo** [comment]
done. next release soon

**Comment by roger21** [comment]
perfect 💯
