### ISSUE TITLE
slideshow

### ISSUE THREAD

**Issue by roger21** [easymodo/qimgv#158]
so i didn't see the slideshow feature, i hope it is planed

**Comment by StevCero** [comment]
Seconded, I would really like to see this feature added.

**Comment by easymodo** [comment]
yeah i'll work on it for the next version

**Comment by easymodo** [comment]
done on `dev` branch ( & will be in the next windows build)

**Comment by easymodo** [comment]
[https://github.com/easymodo/qimgv/releases/tag/v0.9](https://github.com/easymodo/qimgv/releases/tag/v0.9)

**Comment by roger21** [comment]
perfect 💯

**Comment by roger21** [comment]
so, the fact that the slideshow stops automatically when you navigate prev or next is awesome! (and i haven't seen that ever before in other viewers, neither thought of it even though i manually stop the slideshow every time i navigate)
