### ISSUE TITLE
Can't open files with special characters in a parent folder's name

### ISSUE THREAD

**Issue by darsain** [easymodo/qimgv#162]
`×` U+00D7 - multiplication sign
`…` U+2026 - horizontal ellipsis
*I'm sure there's more.*

If any of the characters above are anywhere in any of the parent folder's names, the qimgv will open "empty" - just a blank background with no images to navigate through.

But if they are directly in the image file name, it opens fine.

qimgv 0.8.9

**Comment by easymodo** [comment]
Please redownload, i've ninja-patched it a few hours after release. You probably were quick enough to get the bugged installer

**Comment by darsain** [comment]
Yup, the issue is gone. Thx :)
