### ISSUE TITLE
Maximise/minimise qimgv window issue

### ISSUE THREAD

**Issue by Richard-L** [easymodo/qimgv#165]
Came across your project via ghacks.net.

It's amazing how something as "standard" as an image viewer can feel so fresh, beautiful and exciting. I think you're really on to something special with it. WELL DONE!

On v0.8.9, and Win7-x64, I have this issue a lot:
![image](https://user-images.githubusercontent.com/4934209/74983387-386f3200-5436-11ea-91c8-5bb6a31773b0.png)

When you doubleclick this top window title bar to maximise the app, it's then impossible to minimise it again. Another double-click will keep the window at its max size with the cursor almost impossible to reach for window resizing. A second double-click should downsize the window to its original size and position.

Do you agree?

**Comment by easymodo** [comment]
Yeah i'm aware of this. I'll do something about it in 0.8.10

Just use a fullscreen mode meanwhile

**Comment by easymodo** [comment]
done
https://github.com/easymodo/qimgv/releases/tag/v0.9-alpha1

**Comment by Richard-L** [comment]
Awesome !!! Works perfect.
