### ISSUE TITLE
Wrong version info prompt

### ISSUE THREAD

**Issue by Richard-L** [easymodo/qimgv#167]
Not important at all, and I suppose you know, but just for completeness' sake.

Upon downloading the new "qimgv-x64_0.9-alpha2.zip" from here, qimgv prompts a "welcome to qimgv v0.8.9" message on (and only on) first open.

The app header also still reports this version.

![image](https://user-images.githubusercontent.com/4934209/75189892-7da1a580-574f-11ea-9cf9-248a6bffc2a2.png)

An oversight? Or is it a bad download?

**Comment by easymodo** [comment]
Yeah just ignore it, I forgot to update a value

**Comment by Richard-L** [comment]
This is still going on and honestly confusing. Can you do anything about it?

**Comment by easymodo** [comment]
i've changed it to 0.8.80
it's what many programs do, exapmle: 0.8.80 would be an alpha, 0.8.95 would be a beta 2 or something like that
