### ISSUE TITLE
Right-click on TaskBar icon (Win7) unavailable

### ISSUE THREAD

**Issue by Richard-L** [easymodo/qimgv#169]
I had unpinned qimgv from the Win7 taskbar in order to update to the new v0.9alpha2 (1?).

![image](https://user-images.githubusercontent.com/4934209/75193230-13d8ca00-5756-11ea-8f98-f9652dc2a671.png)
^I can now no longer right-click on the app's taskbar icon in order to re-pin it.

First thought it must be something to do with my system, but all other apps are allowing RMB as expected.

Is it possible this is a new issue?

**Comment by easymodo** [comment]
working fine for me (at least on win8.1)

>Is it possible this is a new issue?

Not sure, i dont think i changed anything related to this. Maybe try the installer

https://github.com/easymodo/qimgv/releases/download/v0.9-alpha1/qimgv-x64_0.9-alpha2.exe

**Comment by easymodo** [comment]
or just drag the exe to a taskbar i think it also works that way

**Comment by Richard-L** [comment]
New alpha3 seems to work again.
