### ISSUE TITLE
error: dependent 'gui\customwidgets\pathselectorwidget.ui' does not exist.

### ISSUE THREAD

**Issue by blakeliu** [easymodo/qimgv#171]
env setting:
1. win10
2. Desktop_Qt_5_9_8_MSVC2017_64bit

QT creator open this peoject, and build.

**Comment by easymodo** [comment]
If you really want to build this on windows you'll have to use msys2 + gcc

get qt and all the depenencies vai msys2, and open the project via `CMakeLists.txt` not the old `.pro` files (i'll remove them)
