### ISSUE TITLE
The procedure entry point ?left@QString@@QEBA?AVI@H@Z

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [easymodo/qimgv#172]
I keep getting this error when I click on the picture when viewing it:

The procedure entry point ?left@QString@@QEBA?AVI@H@Z could not be located in the dynamic link library Qt5Core.dll.

The file is available in the directory where the program is located.
I'm running the portable version.

**Comment by easymodo** [comment]
Can't reproduce this.. works fine with both 0.8.9 and alpha
Maybe you mixed new `.exe` with dlls from previous version? Have you tried reinstalling qimgv from scratch?

**Comment by MNeMoNiCuZ** [comment]
I've just redownloaded and tried v0.9-alpha3 and qimgv-x64_0.9-alpha3-video and I get the same issue.

It also happens when I drag-drop an image into the program (it pops up immediately).

I've not mixed anything up, just unzipped. Do I need to do anything with Qt5Core or put the dll's somewhere manually?

**Comment by easymodo** [comment]
When the right dlls are in the folder with exe it should just work
I don't know what even to suggest tbh..
Do you have a qt sdk installed per chance? Maybe it tries to use dll from there for some reason?

**Comment by MNeMoNiCuZ** [comment]
Nope, sorry, nothing like that installed. Don't have any programming tech in the background.
Just a happy media user that really liked the look of this imageviewer.

It gets a bit frustrating with the popup every time.

Googling a bit gets me some help from stackoverflow:
https://stackoverflow.com/questions/40744629/qt-error-procedure-entry-not-found

And from the QT forums:
https://forum.qt.io/topic/74497/errors-with-qt5core-dll

I've set up the environment variables as they recommended and rebooted, not working.
I've checked the executable with the Dependency Walker and it points to the QT5CORE.DLL in the correct folder.

I'm on Win7 if that does anything.

**Comment by easymodo** [comment]
check if you have the Dell thing, or something of the sort that uses qt5core.dll
search for that file on your system to find out what's causing this

**Comment by easymodo** [comment]
https://forum.qt.io/topic/66447/qfiledialog-problem-entry-point-not-found/12

**Comment by MNeMoNiCuZ** [comment]
Hmm, not using a dell machine. Custom build.

If I remove the Qt5Core.dll it gives me the same error still.

My hardware:
Intel Core i7-2600K @ 3.40GHz
NVIDIA GeForce RTX 2060
