### ISSUE TITLE
Option to set the focus point when toggling 1:1

### ISSUE THREAD

**Issue by darsain** [easymodo/qimgv#174]
It used to be that when toggling 1:1 and the image is bigger than the screen the image would be aligned/snapped to top, but latest patches changed it to middle, so top & bottom parts of the image are not visible without scrolling.

I'd prefer it to revert back as it's annoying to read comic pages like that, but I understand that might just be my preference, so lets add an option? :)

**Comment by easymodo** [comment]
wouldn't Fit Width mode be better suited for reading comics?

**Comment by darsain** [comment]
But fit width stretches the image too much into blurriness.

Also, some pages have graphics that span the whole page and I want to see them in their entirety, so I find myself toggling between 1:1 + fit window quite often.

**Comment by easymodo** [comment]
If you untick `expand images` it wont stretch

Well i guess i could add a centering option somewhere

**Comment by easymodo** [comment]
done but centering stays on by default, as every other viewer behaves this way

**Comment by denzerdhard** [comment]
Is it possible to add an option to toggle into cursor position like with manual zooming as well?

**Comment by easymodo** [comment]
sounds like it would be kinda awkward to use (because you do a keyboard-only shortcut and result depends on another input device)

maybe something like ctrl+click would be better? or even simulate what FSViewer does (zooms only while you hold a mouse button)

**Comment by denzerdhard** [comment]
I thought of something like razer naga with many buttons for mouse only usage, maybe that too specific?

**Comment by easymodo** [comment]
i've decided against hardcoding shortcuts (ctrl+click etc), so there's just gonna be a combobox

i've also added a TopRight mode, maybe someone will find it useful for reading manga or whatever

![image](https://user-images.githubusercontent.com/5484275/76160662-b587f000-6134-11ea-93c5-d274a434db48.png)

**Comment by darsain** [comment]
Uhm, and where is just "Top" option? 😇 meaning "top center".
