### ISSUE TITLE
No printing!  没有打印功能！

### ISSUE THREAD

**Issue by lrcatcn** [easymodo/qimgv#176]
开发者您好，发现此软件没有打印功能！导致在直接浏览所显示的图片时，无法真接打印，建议加上相关的功能，同时系统打印快捷键 CTRL+P 被“软件设置” 功能占用，取消该设置后依然无法打印。

Developer hello, found that the software does not print! It is suggested to add relevant functions. Meanwhile, the shortcut key of CTRL+P for system printing is occupied by the function of "software setting", which still cannot be printed after canceling this setting.

**Comment by lrcatcn** [comment]
Hello, developer, I found that this software has no printing function! As a result, when browsing the displayed pictures directly, it is not possible to print them. It is recommended to add related functions. At the same time, the system print shortcut key Ctrl + P is occupied by the "software settings" function. After canceling this setting, it is still unable to print.

**Comment by easymodo** [comment]
planned for v1.0

**Comment by lrcatcn** [comment]
Thanks

**Comment by easymodo** [comment]
done
