### ISSUE TITLE
Add Crop&Save custom shortcut

### ISSUE THREAD

**Issue by diego10arg** [easymodo/qimgv#177]
Hi,

Today I press X button, select the content I want to keep, press enter to crop and then click on Save.

Would it be possible to define a custom shortcut to "crop&save"?
That would optimize multiple image cropping times.

Thanks! #

**Comment by easymodo** [comment]
https://streamable.com/djh53

You'll be able to right click `Crop` / `Crop & Save` buttons to set focus. After that, when you press enter it will do a selected action.

In addition, Shift+Enter will always do `crop & save` (but this won't be configurable).

**Comment by diego10arg** [comment]
Well, it's nice to have the Shift+Enter option. I believe I will use it much more than right-clicking Crop&Save.

Thanks for your quick response!

**Comment by easymodo** [comment]
>I believe I will use it much more than right-clicking Crop&Save.

it remembers whatever you selected so no need to click it _every_ time
