### ISSUE TITLE
.HEIC support

### ISSUE THREAD

**Issue by Richard-L** [easymodo/qimgv#178]
Apple's annoying format.

Would it be possible to get support?

**Comment by easymodo** [comment]
This nice plugin seems to work fine [https://github.com/jakar/qt-heif-image-plugin](https://github.com/jakar/qt-heif-image-plugin)

I'll include it in the next build

**Comment by easymodo** [comment]
![screenshot 147](https://user-images.githubusercontent.com/5484275/75976970-140a5f80-5ee4-11ea-8092-509247e9fd8d.jpg)


that format also supports "image collections", in such case only the first image will be shown

**Comment by Richard-L** [comment]
Wow, awesome!!!

**Comment by easymodo** [comment]
included in v0.9-alpha4
