### ISSUE TITLE
Ctrl + P to send image to printer

### ISSUE THREAD

**Issue by incker** [easymodo/qimgv#180]
Hello!
I think key combination `Ctrl + P` have to lead to printing image. It is rather common key combination that is in chrome, firefox, exel, and also other image vewers.

Maybe it have sense to make printing  `Ctrl + P` in qimgv also?

P.S. thank you for great image viewer!

**Comment by ben2talk** [comment]
Good request...
Or maybe include help in how to manage a script...
Example:
```#!/bin/bash
gwenview "$1" 
```
Bound to Ctrl_V (for 'view') works to open in gwenview which has print.

Help, another script to do print "$1" bound to ctrl_P

**Comment by easymodo** [comment]
print dialog done
also changed settings to `Ctrl+,` and print to `Ctrl+P`
