### ISSUE TITLE
When default image viewer, all associated exts are considered the same type

### ISSUE THREAD

**Issue by ImportTaste** [easymodo/qimgv#181]
While I want to use qimgv as my default image viewer, not being able to sort my images by type (separating out gifs, pngs, and jpgs) is a big problem. They're all registered as the type 'Program qimgv'. Please fix this.

**Comment by easymodo** [comment]
Try the latest installers  [here](https://github.com/easymodo/qimgv/releases/tag/v0.9-alpha3)

**Comment by ImportTaste** [comment]
Thanks, that worked.
