### ISSUE TITLE
Directory Tree adjustable width

### ISSUE THREAD

**Issue by Richard-L** [easymodo/qimgv#188]
Very good addition!

Is the horizontal thumbnail view still available somehow too though?

On the tree, I'm immediately running into width problems.
![image](https://user-images.githubusercontent.com/4934209/78130747-2f508800-741a-11ea-823f-7d9f80b2cb23.png)

Please consider allowing width adjustment like in windows explorer on mouse hover.

**Comment by easymodo** [comment]
>Please consider allowing width adjustment like in windows explorer on mouse hover.

yeah i'll do this. 
it's just a bit unfinished yet

>Is the horizontal thumbnail view still available somehow too though?

explain..? you mean the one that you get on top window hover? wy would you need that alongside the grid view

**Comment by Richard-L** [comment]
Well it's probably a bit redundant with the tree, you're right. It just looked so cool and I got uses to it :)

**Comment by mendezcode** [comment]
+1 for this

**Comment by markesmith** [comment]
Glad to see expandable width of dir tree will be implemented.

Superb viewer btw. Exactly what I was looking for.

**Comment by easymodo** [comment]
done

**Comment by easymodo** [comment]
[https://github.com/easymodo/qimgv/releases/tag/v0.9](https://github.com/easymodo/qimgv/releases/tag/v0.9)
