### ISSUE TITLE
[REQUEST] Show Directory + Highlight file

### ISSUE THREAD

**Issue by ImportTaste** [easymodo/qimgv#191]
Either as a default part of Show Directory, a config option, or separate function altogether, I'd like a way for the directory of the image to open and then select the file. It's a feature from HoneyView I miss.

The only reason I could see someone not wanting it to be a default part of Show Directory is if the folder has a LOT of image files inside of it, which could soft-lock the explorer window until it loads the data it wants to load before it selects the file.

**Comment by easymodo** [comment]
this is already implemented

**Comment by easymodo** [comment]
next build will have this

**Comment by ImportTaste** [comment]
Also, I have a few questions.

(1) What happened to the alpha4 downloads? I am using it right now and there have been less problems than alpha3.

(2) Do you plan on setting up GitHub Actions or something similar so that each commit will compile a new experimental build?

**Comment by easymodo** [comment]
>What happened to the alpha4 downloads? I am using it right now and there have been less problems than alpha3

there was a dumb ui bug so i temporarily removed it

>Do you plan on setting up GitHub Actions or something similar so that each commit will compile a new experimental build?

i'll look into it, probably a good idea, better than cluttering the releases page

**Comment by ImportTaste** [comment]
Thanks. I'd appreciate a new alpha release in the meantime if it's not too much trouble, having that feature would be really useful for the busywork I'm doing right now.

**Comment by easymodo** [comment]
[alpha5](https://github.com/easymodo/qimgv/releases/tag/v0.9-alpha5)
