### ISSUE TITLE
Wrong app version on titlebar

### ISSUE THREAD

**Issue by mendezcode** [easymodo/qimgv#194]
I assume this is related to the alpha version (using  [v0.9-alpha5](https://github.com/easymodo/qimgv/releases/tag/v0.9-alpha5) on Windows 10 64-bit).

The titlebar shows I believe the latest stable version. Maybe would be a good idea to update the version on titlebar on the alpha version as well, to be able to differentiate the running version.

P.S. _I'm in love with the software, it's beautiful, fast, and very well designed._

![2020-04-12 14-51-07](https://user-images.githubusercontent.com/5881557/79077176-79185880-7ccd-11ea-91a2-058dfc67d936.png)

**Comment by Richard-L** [comment]
I agree this is very confusing, and had reported it before actually https://github.com/easymodo/qimgv/issues/167
