### ISSUE TITLE
Just thank you

### ISSUE THREAD

**Issue by novomesk** [easymodo/qimgv#201]
Hello easymodo,
I am a fan of new image format called [AVIF](https://aomediacodec.github.io/av1-avif/) and your application is able to display AVIF images, when [my plug-in](https://github.com/novomesk/qt-avif-image-plugin) is installed.
![AVIF image in LXImage-Qt](https://raw.githubusercontent.com/novomesk/qt-avif-image-plugin/master/img/app_qimgv.png)
Thank you! (you may close this issue after reading).
Daniel

**Comment by easymodo** [comment]
Hi! Glad you like this program. 
Do you mind if I bundle your plugin with windows build of qimgv?
