### ISSUE TITLE
Folder Tree on Linux

### ISSUE THREAD

**Issue by surml** [easymodo/qimgv#204]
Hi!
I found this piece of usability-art just yesterday and instantly replaced gwenview with it - thx a lot, love it!
Only question: I saw a foldertree-panel on many screenshots and just realized, these where all from windows builds. Did i miss something to enable it on linux or is it not implemented?
If not, do you intend to add that feature? It would be extremely useful to be able to browse the filesystem from within qimgv.

**Comment by easymodo** [comment]
Hi
There are __no__ windows-only features in qimgv. Those screenshots are from testing builds. 
I'm going to release the next version on linux very soon, just one bug left to fix.

**Comment by surml** [comment]
Ok, then I am looking forward to it :-) thank you a lot again!
