### ISSUE TITLE
Qt 5.12 incompatibility due to `storeRelaxed`

### ISSUE THREAD

**Issue by cole-h** [easymodo/qimgv#205]
Hello! Thanks for this fantastic image viewer; it quickly became my favorite.

When I was trying to package the recent 0.9 release for NixOS, I noticed that the build failed due to a change made in https://github.com/easymodo/qimgv/commit/0c8bd56acca85a1a497d9b542621cd7c599203b6 -- specifically, changing `isRunning.store(true);` to `isRunning.storeRelaxed(true);`. `storeRelaxed` appears to have been added in Qt 5.14, which is not yet packaged in NixOS.

I was wondering if you wouldn't be averse to reverting this change to allow building on distributions that are still stuck on Qt 5.12, especially since it doesn't appear to change functionality (in any noticeable way).

**Comment by easymodo** [comment]
thanks, pushed a fix

**Comment by cole-h** [comment]
Thank you, that appears to have worked perfectly!
