### ISSUE TITLE
0.9.0 doesn't open images in maximized window

### ISSUE THREAD

**Issue by krisu5** [easymodo/qimgv#208]
It seems that 0.9.0 doesn't remember window size same way that 0.8.9 and below does.
It remembers the maximized window when opening the exe, but when clicking image from file explorer and opening qimgv again, it goes back to default window size.

OS: Windows 10.

**Comment by darsain** [comment]
Yeah there was a regression and maximized state is forgotten between relaunches in 0.9. Have to maximize every time I open an image.

**Comment by diego10arg** [comment]
So do I, as well.

**Comment by easymodo** [comment]
[v0.9.1](https://github.com/easymodo/qimgv/releases/tag/v0.9.1)
