### ISSUE TITLE
qimgv 0.9.0 ignores image orientation in exif

### ISSUE THREAD

**Issue by Kattus** [easymodo/qimgv#212]
When opening a picture taken with a phone in say portrait mode, qimgv will ignore the image orientation tag and view the picture as the sensor saw it. This was not a problem previously,

![example](https://too.lewd.se/4fafbc5964f3_qimgv_2020-05-02_01-02-47.png)
[Example file](https://user-images.githubusercontent.com/6226312/80847665-c9217580-8c10-11ea-888d-0759c379b183.jpg)

**Comment by easymodo** [comment]
Oof, how did i miss that. Thanks.

Fix in master, do a rebuild

**Comment by Kattus** [comment]
Yup, were compiling while you posted, works now! Thanks :)
