### ISSUE TITLE
Prevent context menu from appearing off the screen

### ISSUE THREAD

**Issue by ImportTaste** [easymodo/qimgv#220]
![image](https://user-images.githubusercontent.com/53661808/81024609-81c9fd80-8e39-11ea-8800-ed93bccf527d.png)

Generally speaking, most apps will have the context menu spawn going upward rather than downward if the cursor is too far down, leftward instead of rightward if the cursor is too far to the right, or both if both are true.

**Comment by easymodo** [comment]
done, it should now behave like native menus

**Comment by ImportTaste** [comment]
@easymodo Hello, it's been a while, and despite my best efforts, I was never able to get this project to compile.

Could you please upload a new pre-release version of qimgv? I'd really like to take advantage of this feature.

**Comment by easymodo** [comment]
hi
here it is
https://github.com/easymodo/qimgv/releases/tag/v0.9.2-alpha

**Comment by ImportTaste** [comment]
@easymodo There's a regression, 'Show in folder' no longer works.

**Comment by easymodo** [comment]
reuploaded

**Comment by ImportTaste** [comment]
> reuploaded

Forgot to reply until now, the issue is fixed, thanks. One question though, why is the OpenGL option in 'Advanced' grayed out?

**Comment by easymodo** [comment]
just ignore it, performs worse that software renderer
