### ISSUE TITLE
Automated compile

### ISSUE THREAD

**Issue by ImportTaste** [easymodo/qimgv#221]
GitHub Actions was recently added, which is a convenient way to make sure your project compiles into artifacts that can be tested every time you commit something. It's also a time-saver in the long run since you won't have to manually compile builds every time you need to put out a new release or just give a test build to someone.

Also, it's not entirely clear how to compile it for Windows at the moment (or at least, not with all the features). It would be easy to figure out a compiling environment if I could just look at the file used for the a GitHub Actions script.

**Comment by easymodo** [comment]
i'll check what's it about

>Also, it's not entirely clear how to compile it for Windows at the moment

Currently using a vm with msys2 repos and custom minimal qt build.

**Comment by ImportTaste** [comment]
You might have to provide the GitHub action script to a download link to your custom minimal qt build, or come up with some patch files that will allow it to modify a qt build it acquires during the build process.

Could you possibly provide me a link to your custom minimal qt build? I should be able to automate the creation of some patch files. Plus it'd just be nice to have.

**Comment by ImportTaste** [comment]
Or instead of a link, you could upload it to my MEGAbox here: https://mega.nz/megadrop/HjCC1M2yt_I

**Comment by easymodo** [comment]
Uploaded. It as an old build though. Unpack to C:/qt5/pkg/ - it may not work when put in other location
