### ISSUE TITLE
No seekbar for webm/mp4 clips and can't move files that contain #

### ISSUE THREAD

**Issue by nick-s-b** [easymodo/qimgv#223]
Hi,

I'm running the very latest `qimgv` that I just compiled and have verified that these two issues are present.

1. When viewing mp4/webm clips, the seekbar immediately disappears and doesn't show up on hover/mouse move. This used to work in all versions prior to 0.9.0

2. I've noticed that you cannot move/copy files that contain''**#**' in the name. Error message says `Source file does not exist.` To verify, rename any file to `test #test.jpg` for example and attempt to move it. Also, you cannot rename such files either (empty file rename message box shows up). 

Thanks!

**Comment by easymodo** [comment]
i've changed the seekbar to only show when you hover the lower part of the window. does it still not show up if you do that?

**Comment by nick-s-b** [comment]
@easymodo ahh, it does. I didn't notice that because it was always at the bottom. 
It makes less sense because as soon as you move your mouse down to interact with it, it disappears. You can't use it this way and can't click on it to seek or use any buttons.

**Comment by easymodo** [comment]
weird, hover area should be larger than the seekbar

**Comment by easymodo** [comment]
fixed file copy (qt surprises again)

hover works fine everywhere i've tried & no one complained yet.. what de/wm are you on?

**Comment by nick-s-b** [comment]
@easymodo Sweet! Thank you. I was suspecting it was a Qt5 bug and they're not properly escaping the string.

As for seek bar... it really should be the way it was. Moving cursor up to reveal something that's down is not very intuitive. And the kicker is that you can't even use it this way since it immediately disappears as you try to use it.

**Comment by Max64hh** [comment]
The error appears with these settings

Thumbnail panel 
Enable panel -> off
Panel position -> Bottom

**Comment by easymodo** [comment]
yep it was broken, thanks
