### ISSUE TITLE
panning mode?

### ISSUE THREAD

**Issue by suntong** [easymodo/qimgv#225]
From the hot key usage I guess that the panning mode is not supported? 

By panning mode I meant to zoom to 1:1 to a super lager image (most of mine generated from `dot`), then move around to see the details, while still able to zoom in and out whenever necessary. 

Comment? thx.

**Comment by easymodo** [comment]
if you mean something similar to fsviewer, then there is no such mode at the moment

but you can press 3 to enter 1:1 mode and then mode around with mouse, touchpad or arrows

**Comment by suntong** [comment]
> move around with ... arrows

But Right/Left arrows are associated with Next/Previous image right? 
Maybe for Next/Previous image, better use PgUp/PgDn like others, maybe?

**Comment by easymodo** [comment]
i think using left-right to switch images feels more natural.  you can rebind everything anyway

**Comment by suntong** [comment]
k. thx.

**Comment by easymodo** [comment]
i'll implement a fsviewer-like mode, it shouldn't be an issue i think. zooming with it feels less clunky
