### ISSUE TITLE
Debian package please

### ISSUE THREAD

**Issue by suntong** [easymodo/qimgv#226]
Since you've already created Ubuntu package, in PPA, why not make one more step forward and make it into would-wide Debian repo as a Debian package? 

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=960198
thx

**Comment by suntong** [comment]
Any thought? 

If you're reluctant to do that, I can try help with the packing...

**Comment by easymodo** [comment]
the thing is i've been thinking about renaming this project soon, so it wouldn't make much sense to put it in debian under the current name

**Comment by suntong** [comment]
OK, gotya. So I'll leave it open until you've done both. thx.

**Comment by idnsunset** [comment]
Still hope this project could appear in Debian official repo ASAP.

**Comment by azzamsa** [comment]
Yes, It's close. https://tracker.debian.org/pkg/qimgv

**Comment by suntong** [comment]
Thanks @azzamsa
