### ISSUE TITLE
Little improvement about scripts on README.md (and code)

### ISSUE THREAD

**Issue by EdwinKM** [easymodo/qimgv#227]
Took me a while. Usually i do not add a shebang (#!/bin/bash) in scripts. The execute (chmod X) flag should be enough?
Created a simple script "echo $@ > ~/loginput.log " and every run it was throwing:
[ScriptManager] Unable not start: "/home/test/bin/loginput.sh"  Make sure it is an executable.

So, maybe clarify the error (in scriptmanager.cpp) and also explicit mention it on README.md

**Comment by easymodo** [comment]
Fixed misleading error message & updated the readme. This should be sufficient i think
