### ISSUE TITLE
Panorama pictures not opening at all

### ISSUE THREAD

**Issue by diego10arg** [easymodo/qimgv#228]
Hi Easy,

Using qimgv 0.9.1 I have been curating my travel pictures and I noticed that pictures taken with Panorama option on my celphone (S7 Edge SM-G935F) are not being open in **qimgv**.

You can download a RAR file containing an example here: https://www.dropbox.com/s/yf60el0noqe2c93/20170929_104246.rar?dl=0

The picture is 7888x3728 pixels, it weights 21Mb.

If you need anything else, just let me know!

Thanks in advance
Diego

**Comment by easymodo** [comment]
this was quite a headache.. fixed, hopefully
