### ISSUE TITLE
Suse Thumbleweed: Video does not work

### ISSUE THREAD

**Issue by EdwinKM** [easymodo/qimgv#231]
Installed qimgv using the official repo

use:
qimgv /directory/with/movies

result:
motage screen with movie previews (working)

use:
qimgv /path/to/movie/file

result:
message: [VideoPlayerInitProxy] Error - could not load player library
Transparent video screen is visible

Compiled my own versions (used: "zypper source-install -D qimgv" to get the Suse patches". Applied only "qimgv-includepath.patch" and "qimgv-nosharedlib.patch")
Was a bit toying around. The "createPlayerWidgetFn fn" seems also null?

**Comment by easymodo** [comment]
can you check just in case, do these files exist on your system?

```
/usr/lib/libqimgv_player_mpv.so
/usr/lib/libqimgv_player_mpv.so.1
/usr/lib/libqimgv_player_mpv.so.1.0
```

**Comment by easymodo** [comment]
just looked at it [https://build.opensuse.org/package/view_file/graphics/qimgv/qimgv-nosharedlib.patch?expand=0](https://build.opensuse.org/package/view_file/graphics/qimgv/qimgv-nosharedlib.patch?expand=0)

This will break QLibrary (the way i'm using it anyway. It expects a file
`    playerLib.setFileName("qimgv_player_mpv");`

I'm not sure why opensuse folks did this.. Maybe someone did not like that i\m creating 3 additional files? 

Try building without that patch

**Comment by EdwinKM** [comment]
first of all: playerLib.setFileName("/home/test/TEMP/qimgv-master/build/qimgv_libs/qimgv_player_mpv/libqimgv_player_mpv.so"); fixed it. 

Tried a dev snapshot with ONLY the OpenCV patch (apply it manually) and it is also broken.
The OpenCV patch is really needed to make it compile. The  qimgv-nosharedlib.patch  does not make a difference?

ls -l /usr/lib/libqimgv_player_mpv*
-rw-r--r-- 1 root root 293752 May 18 12:45 /usr/lib/libqimgv_player_mpv.a
lrwxrwxrwx 1 root root     24 May 18 12:33 /usr/lib/libqimgv_player_mpv.so -> libqimgv_player_mpv.so.1
lrwxrwxrwx 1 root root     26 May 18 12:33 /usr/lib/libqimgv_player_mpv.so.1 -> libqimgv_player_mpv.so.1.0
-rwxr-xr-x 1 root root 193656 May 18 21:26 /usr/lib/libqimgv_player_mpv.so.1.0

**Comment by lgbaldoni** [comment]
> I'm not sure why opensuse folks did this.. Maybe someone did not like that i\m creating 3 additional files? Is that considered "bad"?

At the time I probably didn't want to create two subpackages (library and devel) only for a single application.
However the default approach has a few unusual features:

- qimgv doesn't actually link to libqimgv_player_mpv
- there is no other application using this library and even if it did, no public headers come with it
- given the way shared libraries are normally packaged, one has to install both the library package and the devel one (containing the .so)

> This will break QLibrary (the way i'm using it anyway. It expects a file
playerLib.setFileName("qimgv_player_mpv");

How about creating an unversioned plugin instead? (ideally to be put into /usr/lib/qimgv)

**Comment by easymodo** [comment]
>qimgv doesn't actually link to libqimgv_player_mpv

When i just link to mpv the load times become very slow, like 1-2seconds slower. It is okay for video player but not for this kind of application. That's why the .so file, to load mpv stuff ondemand. Maybe there's a better way, i don't know

>How about creating an unversioned plugin instead? (ideally to be put into /usr/lib/qimgv)

I'll look into it

**Comment by lgbaldoni** [comment]
The submission window for openSUSE Leap 15.2 is closing fast. I'm in two minds on how to address the problem right now.

**Comment by EdwinKM** [comment]
> @EdwinKM Could you please file a bug report on bugzilla.opensuse.org too?

created: https://bugzilla.opensuse.org/show_bug.cgi?id=1172315

**Comment by lgbaldoni** [comment]
Those patches work for me.
