### ISSUE TITLE
[feature request] Allow changing location of thumbnail cache

### ISSUE THREAD

**Issue by rieje** [easymodo/qimgv#245]
Simple feature request--allow changing location of thumbnail cache. Useful for performance reasons in particular (e.g. storing them in /tmp or RAM, since I don't need them to be cached indefinitely).

**Comment by easymodo** [comment]
makes sense, will do

**Comment by easymodo** [comment]
qimgv.conf:

```
cacheDir=/path/to/whatever
```

**Comment by rieje** [comment]
Great. How about an action to clear/update thumbnail cache? E.g. I like to rotate an image and save it. To update the thumbnail of any saved edits, restarting qimgv is not enough and cacheDir needs to be cleared.
