### ISSUE TITLE
A way to ignore PDFs

### ISSUE THREAD

**Issue by nick-s-b** [easymodo/qimgv#247]
Hi,
For some reason, newer versions of `qimgv` load PDF files. Unfortunately, only the first page is displayed and it's rendered rather poorly. I'd like to completely disable viewing of pdfs if possible. Something along the lines of "ignore PDFs" in preferences.

Thanks!

**Comment by easymodo** [comment]
Noticed this too.. Probably was added in qt 5.15 for some reason
