### ISSUE TITLE
Resize by Percentage

### ISSUE THREAD

**Issue by homeisfar** [easymodo/qimgv#249]
Hi,
I think a great feature would be to choose to resize an image by %. I already have a working prototype and I can soon make a pull request, too, after I make sure there are no corner case or rounding issues.

Demo:
![qimgv resize percent](https://user-images.githubusercontent.com/5819347/87468917-6e30d500-c5e8-11ea-81d6-ab271f9a17ac.png)

![qimgv resize percent2](https://user-images.githubusercontent.com/5819347/87469333-22326000-c5e9-11ea-952e-001cc482f8ae.png)

Modifying by absolute size remains the default option.

Another UI implementation which would be closer to macOS Preview or Photoshop's is to have a drop menu selection instead of radio buttons. Such that instead of a new percent spinbox, the width/height spinboxes would be repurposed into percent spinboxes, you could adjust their width/height % independently (or simultaneously if the aspect ratio cheeckbox is selected, of course).

Let me know what you think. Thanks.

**Comment by easymodo** [comment]
Hi

The current resize dialog is crappy and unfinished, so any PR with improvements would be welcome (just make sure to use dev branch)

If you think there's a use case for percent resizing then why not. I do not think a few checkboxes will make the ui worse

**Comment by homeisfar** [comment]
PR has been opened.
https://github.com/easymodo/qimgv/pull/250

This is my first time touching Qt code, so I mostly just tried to follow what already existed. I think next time I have an opportunity I will want to enable the resize filter option to allow resize to the nearest neighbor.
