### ISSUE TITLE
[BUG] GIF bug, partial play on medium-large resolutions, program freeze

### ISSUE THREAD

**Issue by ragouel** [easymodo/qimgv#262]
qimgv 0.9.1
qt5 5.15.1
opencv 4.5.0
Linux 5.4.72

Program only plays through first few frames of a GIF image in resolutions greater than ~1000x600. Upon clicking [pause frame] program completely freezes.

![palantir-demo4](https://user-images.githubusercontent.com/7093002/96692796-21029300-138f-11eb-9d38-7543d62a2b4a.gif)

**Comment by easymodo** [comment]
I think this is a bug in the recent Qt..
Affects other software like gwenview

**Comment by easymodo** [comment]
works again with qt 5.15.2
