### ISSUE TITLE
.xcf (Gimp) support

### ISSUE THREAD

**Issue by CHJ85** [easymodo/qimgv#263]
Hi there. I just found this image viewer.
I like it a lot. But would it be possible to add support for the Gimp project file .xcf?
That'd be great.
I already have kimageformat-plugins installed. I'm on KDE btw. So technically it should be doable, because this is a Qt app and .xcf thumbnails show up just fine in the file browser.
Thanks in advance.

**Comment by easymodo** [comment]
Hi
If you are on linux you can install `kimageformats` package, that will give you xcf support. Despite the name it has no kde dependencies
For windows, i'll try to include it for v0.9.2 if possible

**Comment by easymodo** [comment]
just read your edit
weird, with that package it should work, at least it works for me..

**Comment by CHJ85** [comment]
Well. It does support Gimp 2.8 files. Not 2.10 files. But again. The thumbnails in Dolphin file browser work just fine.

**Comment by CHJ85** [comment]
Just to clarify. The reason I know this is because I found an old .xcf file from back when I had Gimp 2.8.

**Comment by easymodo** [comment]
Ok so i've tested it a bit. It works on 20.10. 
You can either upgrade your distro or somehow get the latest `kimageformat-plugins` package

![screenshot 401](https://user-images.githubusercontent.com/5484275/97092615-0dd11b00-164e-11eb-917f-a7a1e460de07.jpg)

**Comment by CHJ85** [comment]
Thanks a bunch! I've now upgraded to 20.10 and it works like a charm.
Seriously. Thank you.
