### ISSUE TITLE
WEBM files turn transparent after opening. 

### ISSUE THREAD

**Issue by user198** [easymodo/qimgv#264]
Last night I started to experience issues with playing WEBM files. When opening the file, the window goes transparent besides the title bar (as seen in the attached file) and if you move your mouse to where the media controls would be, it will show them. I cleared the config folder as well as purged and reinstalled and the issue persists. I think i did a apt update and upgrade yesterday earlier in the day, perhaps it is a bug caused by the ubuntu updates? All other file types work fine, only webm is having the issue.
![Screenshot_20201025_105028](https://user-images.githubusercontent.com/45182954/97111800-1f9ad880-16b7-11eb-9f47-eff8d8fd9a58.png)
)
Kubuntu 20.04
qimgv 0.9.1
qt5 5.12.8

**Comment by easymodo** [comment]
I did a small update yesterday, but it worked in a vm.  In fact i've just tested it again on 19.04, works..
Try running qimgv from terminal, open webm then post the error

**Comment by user198** [comment]
I don't know if I did it right but I just put qimgv in the terminal then the file path and it brought the image so I assume it is correct. 
I am geting
Plugin at: "/build/qimgv-iAZylS/qimgv-0.9.1-13-74cbab5/debian/qimgv/usr/lib/qimgv/player_mpv.so" does not exist.
Plugin at: "/build/qimgv-iAZylS/qimgv-0.9.1-13-74cbab5/debian/qimgv/usr/lib/qimgv/player_mpv.so" does not exist

![Screenshot_20201025_120750](https://user-images.githubusercontent.com/45182954/97112481-efedcf80-16ba-11eb-83cb-18f923a6cb99.png)

**Comment by easymodo** [comment]
fix is up, please update
