### ISSUE TITLE
empty window

### ISSUE THREAD

**Issue by whoizit** [easymodo/qimgv#266]
![image](https://user-images.githubusercontent.com/359276/98874202-d4d8d900-248a-11eb-96a8-20181a674400.png)

Void Linux (updated)
qimgv-0.9.1_1
wayland/sway

any suggestions?

**Comment by easymodo** [comment]
what's the problem? this is how it looks without any file opened
you can right click for menu or press enter for directory view

or is it actually not displaying an image

**Comment by whoizit** [comment]
This is the strangest behavior I have ever seen. It is counter-intuitive. It should display something by default. Like the home directory or some message.For example like an empty vim window (it is not really empty and shows a useful message). I should press Enter?  But why I should do this on empy window?

**Comment by easymodo** [comment]
there will be some kind of welcome screen in v0.9.2 (maybe only on first run) so new users wont be as confused

if that's not enough, there's already a `start in folder view` option

![image](https://user-images.githubusercontent.com/5484275/98891042-fe532e00-24a5-11eb-8e69-f7ba9cafc1d0.png)

**Comment by markesmith** [comment]
Just a guess but could the OP mean seeing the empty thumbnail view is expected only if a folder is selected from the directory tree and is empty? 

Here is a view of a sample directory: 

I have placed some images in the qimgv folder so something is displayed in the thumbnail view. Note the sub directories are not displayed as folder icons in the thumbnail view. 

![image](https://user-images.githubusercontent.com/64022365/98921717-8696fa80-24c9-11eb-89b1-24ad83b49b4b.png)

If, however, those images are placed inside one of the sub directories of the qimgv folder, the thumbnail view is now empty:

![image](https://user-images.githubusercontent.com/64022365/98921791-99113400-24c9-11eb-8032-e6b808aa8545.png)

Wouldn't you expect to see the sub directories as folder icons in the thumbnail view if a folder contains sub directories? 

A very minor issue but one that might make the viewer a little more useable in terms of browsing very nested directories. 

Best regards, MES

**Comment by easymodo** [comment]
folders are already done on the dev branch
