### ISSUE TITLE
How to define distinations of "quick copy" and "quick move"

### ISSUE THREAD

**Issue by realwebsnail** [easymodo/qimgv#267]
Ver 0.9.1 under Windows 10. when I use shotcut key C or M to quick copy | move a picture, there is a popup list show 9 distinations that copy to. but all 9 list items are point to my home dir, I can't find how can modify or define these item. does it unfinish yet ?

**Comment by easymodo** [comment]
click on the folder icon

![2020-11-22-134901_1920x1080_scrot](https://user-images.githubusercontent.com/5484275/99902877-8ff24500-2cc9-11eb-9ea1-4fc935b59aaa.png)

**Comment by realwebsnail** [comment]
> 
> 
> click on the folder icon
> 
> ![2020-11-22-134901_1920x1080_scrot](https://user-images.githubusercontent.com/5484275/99902877-8ff24500-2cc9-11eb-9ea1-4fc935b59aaa.png)

Danke！
