### ISSUE TITLE
shuffleEnabled gets set to true; there is no UI option to disable it

### ISSUE THREAD

**Issue by nick-s-b** [easymodo/qimgv#269]
Hi,
I updated my Arch install and I also compiled a new version of `qimgv` and after going through some folders of pictures, I noticed that they're not sorted properly. No matter what option I chose in preferences, it would always show pictures in a random order. I looked at the .conf file and searched for "random" but didn't see anything. I then checked out my backups from before I upgraded and I noticed this option:
````
shuffleEnabled=true
````
Setting this to false fixed the issue. It nearly drove me insane trying to troubleshoot this.

1. This option should not be introduced into `qimgv.conf` randomly, with an update of the program
2. This option should not override user-set 'File sorting' option
3. If this is useful to someone, it should be exposed in the UI (if it has to be in the program, I'd put it under "File sorting" as "Random" option and then not have it as a separate key-value in the conf).

Thanks!

**Comment by easymodo** [comment]
Hi
The question is, why the hell did i put shuffle state in settings.. This is dumb. It should just be reset on launch
Also that line probaby wasnt introduced with update, you could have accidentally pressed `S`

And yeah i'll put an indicator somewhere

**Comment by nick-s-b** [comment]
Hi @easymodo !

> you could have accidentally pressed S

That's definitely possible! There was no indication of it on the screen and it happened right after the update so it could have lead me down the wrong path of the root cause.

I've removed it from my shortcuts since I never use it so it won't happen again. I still think that putting it in that File Sorting drop down menu is better than giving it its own key-vale pair option. Thank you so much. I'll close this issue.
