### ISSUE TITLE
SVGZ files (compressed SVG) aren't properly displayed.

### ISSUE THREAD

**Issue by MR-Diamond** [easymodo/qimgv#277]
I attempted to open an SVGZ file (eg this one https://raw.githubusercontent.com/pablojorge/nmap-os-db-analyzer/master/sample.svgz) with qimgv, but I found out that is displayed as garbage:

![qimgv-SVGZ](https://user-images.githubusercontent.com/32249442/104089536-31c8f380-5270-11eb-9a39-355c3af801ac.png)

Open it with another Qt image viewer (in this case KolourPaint) this file is properly displayed instead:

![Kolourpaint-SVGZ](https://user-images.githubusercontent.com/32249442/104089556-545b0c80-5270-11eb-9f7d-133727f8bd16.png)

**Comment by easymodo** [comment]
Sorry for taking too long

Juist tested and it works for me. It's just zoomed out by default, press `Space` or `3` to switch to 1:1 mode
