### ISSUE TITLE
There is a bug in 0.9.1

### ISSUE THREAD

**Issue by iesvme** [easymodo/qimgv#278]
![image](https://user-images.githubusercontent.com/16969250/104333445-315c8100-552c-11eb-9bf2-5de8efe4bdfb.png)
![image](https://user-images.githubusercontent.com/16969250/104333466-38838f00-552c-11eb-99b3-c80be8c5dd01.png)

System: win10 1809 LTSC x64
Language: Chinese

**Comment by easymodo** [comment]
what is wrong exactly?  click on the folder to change location

**Comment by iesvme** [comment]
oh, Im so sorry. I get it now.
Thank you very much!

easymodo <notifications@github.com> 于 2021年1月13日周三 00:02写道：
