### ISSUE TITLE
Autohide cursor

### ISSUE THREAD

**Issue by travankor** [easymodo/qimgv#281]
Autohide the mouse cursor after a mouse inactivity timeout. This would be similar to mpv’s cursor autohide.

**Comment by easymodo** [comment]
there is an autohide though? 
is it not working for you?

**Comment by travankor** [comment]
Apparently, I already have the setting toggled on. Doesn't seem like it works on Wayland. Maybe a QT bug?

**Comment by easymodo** [comment]
ah, yes, i've disabled it on wayland. had lots of issues with mouse hover events
but that was a year ago, need to check again with the latest qt

**Comment by easymodo** [comment]
>I can reproduce if I don't move the cursor after I initially start qimgv
> Maybe a QT bug?
Yes, unfortunately under wayland QCursor::pos() incorrectly returns (0,0) until you move a mouse once. I'll try to come up with a workaround

**Comment by easymodo** [comment]
done

feel free to reopen if it's still broken for you
