### ISSUE TITLE
Why do you check for file write permission to perform file operations?

### ISSUE THREAD

**Issue by dpalacio** [easymodo/qimgv#292]
A file doesn't have to be writable to be able to be moved, renamed or deleted. If I remove this check I can delete my read only files anyway. So why are these checks here?

File checks in question are here:
qimgv/utils/fileoperations.cpp

```
qimgv/utils/fileoperations.cpp-void FileOperations::removeFile(const QString &filePath, FileOpResult &result) {
qimgv/utils/fileoperations.cpp-    QFileInfo file(filePath);
qimgv/utils/fileoperations.cpp-    if(!file.exists()) {
qimgv/utils/fileoperations.cpp-        result = FileOpResult::SOURCE_DOES_NOT_EXIST;
qimgv/utils/fileoperations.cpp-    } else if(!file.isWritable()) {
qimgv/utils/fileoperations.cpp:        result = FileOpResult::SOURCE_NOT_WRITABLE;
```

Did you intend to check for the parent folder write permissions instead? Or maybe it is a Windows only issue?

**Comment by easymodo** [comment]
>Windows only issue?

just checked and `QFile::remove(filePath)` fails on read-only file (dir itself is writable)

>check for the parent folder write permissions instead

yeah you're right, i probably just assumed it works the same way on linux

**Comment by dpalacio** [comment]
The command line `rm` tool does give you a warning but it doesn't actually fail or block you. The dolphin file manager doesn't treat read only files any different.
