### ISSUE TITLE
repository does not work with xenial

### ISSUE THREAD

**Issue by mjackmjackmjack** [easymodo/qimgv#294]
When installing in linux mint following your indications I get this :
sudo add-apt-repository ppa:easymodo/qimgv
'Ce PPA ne prend pas en charge xenial'
Impossible d'ajouter le PPA: ''Ce PPA ne prend pas en charge xenial''.

I am too noob to find another way to install it by myself, but I use it on my other windows computer and It works almost exactly how I need. 

Any suggestions?

**Comment by easymodo** [comment]
The oldest packages in repo are for 19.04

Consider upgrading your distro. Xenial is what, almost 5 years old now?
