### ISSUE TITLE
Cropping not working properly

### ISSUE THREAD

**Issue by diego10arg** [easymodo/qimgv#297]
Hi,

I'm using 0.9.1 and I found that when I try to crop sometimes it does not work.

Steps to reproduce:

1. Open image
2. Press X (to enter Crop Mode)
3. Press Control+A (to select all the image)
4. Choose an Aspect Ratio, for example 16:10
5. Press Enter to accept cropping and saving the image (without clicking on the image)

It will cancel the cropping mode with no cropping applied to the image.

Thanks in advance!

**Comment by easymodo** [comment]
well that was dumb

thanks
