### ISSUE TITLE
[Windows portable] Could not load player_mpv.dll from plugins/

### ISSUE THREAD

**Issue by piyo-gh** [easymodo/qimgv#302]
I am using Windows portable version. When I load video files, I get eror message "Could not load player_mpv.dll from plugins/"
But if I set current directory (working directory) to exefile directory, I can load video files without problems.

It seems that qimgv searches plugins folder from `[current directory]\plugins\`, but I think it should be `[application directory]\plugins\`. Since mpv.exe path is already using `QCoreApplication::applicationDirPath()`.

thanks,

**Comment by easymodo** [comment]
yes, i messed up there

reuploaded the [fixed version ](https://github.com/easymodo/qimgv/releases/tag/v0.9.2-alpha2)
