### ISSUE TITLE
step over/Pass through? folder to view

### ISSUE THREAD

**Issue by AliSwitch** [easymodo/qimgv#304]
can you make it when view the last picture in a folder , then view pictures in the next  folder,which in one root folder?it will be very convenience for view Comics。
thanks for your work

**Comment by easymodo** [comment]
Thanks for reminding, someone already requested this feature but i completely forgot about it

**Comment by easymodo** [comment]
Done.

You can switch between nearby folders via `Shift+Left` / `Shift+Right`, or automatically with arrows / mousewheel (off by default)
