### ISSUE TITLE
Next/prev image actions have non-sequential movement

### ISSUE THREAD

**Issue by dpalacio** [easymodo/qimgv#305]
In my system with qimgv (git-master) loading the next or previous image in a folder loads a picture that doesn't follow the current one. For example, if the current picture is the 5th out of 10, it may not load the 4th or the 6th.

System information:
Debian Bullseye (testing)
qimgv: git-master

[qimgv-non-sequential.zip](https://github.com/easymodo/qimgv/files/6329749/qimgv-non-sequential.zip)

**Comment by easymodo** [comment]
Do you have shuffle mode enabled? Try pressing `S`

**Comment by dpalacio** [comment]
Yes, thank you!
I didn't see a mention of that feature in any part of the user interface besides, just a few minutes ago, in the shorcuts editor. If that appreciation is accurate, this issue should be retitled "Shuffle mode state isn't visible in the user interface"

**Comment by easymodo** [comment]
yeah this is the second time someone thought it was a a bug

i'm changing this hotkey to something harder to hit accidentally

**Comment by dpalacio** [comment]
Back in issue #269 you had considered to disable shuffle mode on startup. I think that is good idea.

**Comment by easymodo** [comment]
just done exactly that

**Comment by dpalacio** [comment]
Great, thanks! You might want to revert the hotkey commit. And a bit offtopic question: are you a Windows/Mac/KDE/Other dev? If you were a KDE person I would like you to be influential in shaping the future of the desktop.

**Comment by easymodo** [comment]
No, I'm just doing this project in my free time. Not contributing to anything atm. But it use kde, yes..
