### ISSUE TITLE
WebP is not displayed, not parsed

### ISSUE THREAD

**Issue by df-line** [easymodo/qimgv#308]
I'm running qimgv under Ubuntu 20.10, and this nice little image viewer doesn't display any webp images. It doesn't even parse them from the current directory, so when there are 2 jpegs and 2 webp together in a directory the title says [1/2] instead of [1/4].

I saw an earlier closed issue (#124) regarding problems with displaying webp images, maybe they are related. 

```
qimgv output: 

qimgv 0.9.1 - A fast and configurable image viewer. Written in qt5.
Website: https://github.com/easymodo/qimgv
License: GNU GPL v3

Usage:
   qimgv [options] [file or directory]

Options:
   --help  or  -h    Print this message and exit

Enabled build options:
    "USE_MPV"
```

**Comment by easymodo** [comment]
try `sudo apt install qt5-image-formats-plugins`

**Comment by easymodo** [comment]
or just update qimgv (i've just uploaded a new version which should include that formats pack)
```
sudo apt update
sudo apt upgrade
```

**Comment by df-line** [comment]
The formats-plugin solved my issue. Thank you!

**Comment by MichaelLawton** [comment]
Installing `qt5-qtimageformats` on Fedora did the trick for me. However I think qimgv should display an error or warning if this is missing when opening a WebP file, instead of just a blank screen? Or maybe make it a required or optional package dependency? (maybe this is a Fedora packaging issue)
