### ISSUE TITLE
GitHub Actions compiler

### ISSUE THREAD

**Issue by ImportTaste** [easymodo/qimgv#315]
With how difficult it is to compile this project (which may still be using a modified version of Qt that can't be distributed) I think it would be a good idea to have GitHub Actions do a compile operation with every commit.

I looked into it, and you can set up hidden env variables for tokens, which means you can store the modified Qt in a private repo and the build job can retrieve it using the token. In other words, it would never be exposed to public view but can still be used for compiling qimv, and the resulting artifacts can be downloaded by everyone.

**Comment by easymodo** [comment]
I still have to look into github actions, never used it

>using a modified version of Qt that can't be distributed

It's a minimal qt build but that's just for reducing dll size. Theres nothing special about it, i can put it into a public repo

qimgv will also compile with whatever qt that comes in msys2

**Comment by ImportTaste** [comment]
> I still have to look into github actions, never used it

It's a lot simpler than it looks. A yml instruction set puts together a consistent build environment from scratch each time, automatically. It just takes a little bit of trial-and-error.

> It's a minimal qt build but that's just for reducing dll size. Theres nothing special about it, i can put it into a public repo

I must have been misremembering what made the project difficult to compile. In any case, I hope you can get it working.

**Comment by easymodo** [comment]
I think it works.. done?
Also now there is an build script for msys, if you want to build locally

**Comment by ImportTaste** [comment]
@easymodo My apologies, by the way, I didn't realize I submitted this issue twice.
