### ISSUE TITLE
Request - "Simple" print support

### ISSUE THREAD

**Issue by abrasion66** [easymodo/qimgv#316]
Is there any plan to add a print support ?

**Comment by easymodo** [comment]
yeah working on it
the fact that i dont have a printer kinda gets in the way lol

**Comment by abrasion66** [comment]
use a pdf printer maybe ?

**Comment by easymodo** [comment]
Something like this..  not too simple? I dont print that much, not sure what stuff folks usually need on a print dialog

<img width="589" alt="Screen Shot 2021-06-14 at 6 51 41 PM" src="https://user-images.githubusercontent.com/5484275/121921406-a59c8a00-cd41-11eb-8b71-6d4f9ee5463e.png">

**Comment by abrasion66** [comment]
Portrait / landscape
Print in "color" or "gray level" (gray is useful l for children coloring)
Scale to fit best in "full page"

A preview of final render maybe great as extra feature

**Comment by easymodo** [comment]
done

<img width="657" alt="Screen Shot 2021-06-15 at 1 11 06 PM" src="https://user-images.githubusercontent.com/5484275/122035489-2f4c6600-cddb-11eb-84f1-168865f3acce.png">

**Comment by abrasion66** [comment]
Tyvm, it's perfect (for me at least)

**Comment by vicioussn** [comment]
Hi, How can I open print dialog in 0.9.1?

**Comment by easymodo** [comment]
hi

Havent released it yet, but you can use this build. Print dialog is Ctrl+P

https://www.dropbox.com/s/4ghvjmnnnl84tw1/0.9.2-dev-2021-06-21.7z?dl=0
