### ISSUE TITLE
Image thumbnail won't show if file contains < or >

### ISSUE THREAD

**Issue by Qwerty-Space** [easymodo/qimgv#319]
Title says it all.  If an image is < or > in the filename, the thumbnail won't load.

version 0.9.1-1

![image](https://user-images.githubusercontent.com/6967592/124291267-5087b300-db4c-11eb-998f-5c7fd8f7b9ab.png)

Removing the character results in the thumbnail showing
![image](https://user-images.githubusercontent.com/6967592/124291437-7a40da00-db4c-11eb-8221-a3792a262d0f.png)

**Comment by easymodo** [comment]
It seems i've already fixed this sometime ago..  please use a newer build 

`0.9.2-alpha2` if you're on windows, `qimgv-git` from aur if you're on archlinux

**Comment by Qwerty-Space** [comment]
Will this be released to the non-git package?

**Comment by easymodo** [comment]
yes when i finish 0.9.2
