### ISSUE TITLE
Exiting fullscreen repositions the window; transparency doesn't work

### ISSUE THREAD

**Issue by oredaze** [easymodo/qimgv#326]
0.9.1 on Void Linux
I am experiencing 2 bugs and have 2 suggestions:
1. After you exit fullscreen the window gets moved to the top left corner. (I am using fvwm3) (edit: I tried openbox and it does not happen there, but it does not happen under fvwm with other image viewers)
2. Transparency grid option and hotkey do nothing...

1. One suggestion I have is to be able to toggle the "fullscreen info overlay" (so that we have a clean image view, but still be able to see the info when needed). Or maybe even 1-time-show of the overlay.
2. The 3 icons on the thumbnail panel are redundant if the panel is at the bottom, sorry for the stupid remark, but you have them in 2 other places + hotkeys, so 4 total...

Other than that I am extremely impressed with qimgv, after trying out all the viewers out there, this one is the best. Thank you for your work.

**Comment by easymodo** [comment]
>After you exit fullscreen the window gets moved to the top left corner

Fixed. 
There's still a little bug with geometry save/restore (window shifts a little bit if you open-close qimgv). But i think that's on fvwm, probably related to how it draws window border. KDE/gnome/xfce/macos/w*ndows - no problem there

>The 3 icons on the thumbnail panel are redundant 

I could remove them while you are in fullscreen mode, but that would be a bit of a confusing ux.. I'll think about that

>Transparency grid option and hotkey do nothing...

a victim of refactoring. forgot about that thing

**Comment by oredaze** [comment]
Excellent, you are doing quality work.
I would hope for the 3-rd one, if I may. If not - god bless anyway.

**Comment by easymodo** [comment]
toggle for infobar done (no default shortcut, bind it to whatever you want)

**Comment by oredaze** [comment]
Thank you so much.
