### ISSUE TITLE
EXIF comment

### ISSUE THREAD

**Issue by eddiezato** [easymodo/qimgv#330]
It would be useful if the EXIF panel could show the contents of the `Exif.Photo.UserComment` tag in addition to the other stuff.

**Comment by easymodo** [comment]
done

**Comment by eddiezato** [comment]
Thanks! BTW, all the fields in the EXIF panel are editable, although they don't modify the image file. Dunno if this is supposed to be that way.

**Comment by easymodo** [comment]
Made it a bit nicer. And removed the misleading LineEdit

![screenshot 515](https://user-images.githubusercontent.com/5484275/132683827-0e4682e1-750a-4d4f-b0ad-a32e70896b3d.png)

**Comment by eddiezato** [comment]
@easymodo 
```
error: '../qimgv/res/icons/common/overlay/info16.png', needed by 'qimgv/qimgv_autogen/EWIEGA46WW/qrc_resources.cpp', missing and no known rule to make it
```

**Comment by easymodo** [comment]
added

**Comment by githlp** [comment]
> Made it a bit nicer. And removed the misleading LineEdit
> 
> ![screenshot 515](https://user-images.githubusercontent.com/5484275/132683827-0e4682e1-750a-4d4f-b0ad-a32e70896b3d.png)

How do i get all that EXIF Tags in my ? Mine is very minimal, though the infos are there as checked with exiftool -a :

![scrot_qimgv_exif_info](https://github.com/user-attachments/assets/e48de19c-539d-4871-a215-b136fe350a64)

**Comment by githlp** [comment]
ah, adjust documentinfo.cpp to my needs and then build from source i guess ..

**Comment by easymodo** [comment]
> ah, adjust documentinfo.cpp to my needs and then build from source i guess ..

yeah it's hardcoded
