### ISSUE TITLE
[Feature Request] Basic actions for directories like rename, delete, etc.

### ISSUE THREAD

**Issue by rieje** [easymodo/qimgv#332]
Just a request for basic actions for directories like rename, delete, etc. A lot of useful actions are available for acting on file already, but just basic actions that would be applicable for a directory as well would go a long way in not requiring both a file manager to do the work that qimgv can do. Right now I'm sifting through many (directories) containing hundreds of images but have a file manager on the side to do the basic actions, which is cumbersome for workflow.

**Comment by easymodo** [comment]
- Folder renaming done.
- Folder delete/trash should already work.
- For moving there's drag'n'drop.  I will add copy-pasting and batch rename in later releases.
