### ISSUE TITLE
qtraw

### ISSUE THREAD

**Issue by eddiezato** [easymodo/qimgv#333]
@easymodo 
Sorry, this may be isn't very related to qimgv itself. Could you please share your commands to build `qtraw` for qimgv on windows?

**Comment by easymodo** [comment]
Just the regular clone & build

```
git clone https://gitlab.com/mardy/qtraw.git
cd qtraw
mkdir build && cd build
qmake ..
make -j4
```

Though i've had to add a definition to `libraw_datastream.h` in order for this to compile (it's somewhere in your msys folder) 
```
#define getc_unlocked _fgetc_nolock
```

**Comment by eddiezato** [comment]
> `#define getc_unlocked _fgetc_nolock`

That's what I need. Thanks!

**Comment by eddiezato** [comment]
This is unfortunate, but adding `qtraw.dll/libraw-20.dll` doesn't make my qimgv build support raw images. 🤔
