### ISSUE TITLE
Modifications made in folder view automatically saved despite not explicitly saved

### ISSUE THREAD

**Issue by rieje** [easymodo/qimgv#339]
In folder view, a photo is hovered and an action like `rotateLeft` is performed. The thumbnail shows the reflected change--the photo is rotated left. On quit, this modification is saved despite not explicitly saving the changes.

What I expected: If a photo is changed in such a way in folder view, there should be an indication that the change was modified (something like a prompt for "Unsaved edits" like you would get normally when editing a single image in main window view). It should also never save any photos automatically without the user explicitly saving.

**Comment by easymodo** [comment]
there's now a confirmation when you press the corresponding shortcut
