### ISSUE TITLE
Crashes when right-clicking for context menu in middle/bottom portion of main view window 

### ISSUE THREAD

**Issue by rieje** [easymodo/qimgv#340]
qimgv crashes when right-clicking for context menu in middle/bottom portion of main view window. I get the `Segmentation fault (core dumped) qimgv` error from the terminal. It never crashes when right-clicking the top portion of the main view window.

At first, I assumed it would randomly crash at any part of the window, but I did some trial and error and this is the behavior I seem to be consistently experiencing.

**Comment by easymodo** [comment]
cant reproduce over here

i've added some checks in the portion where it could crash, can you rebuild and report back if it's fixed?

**Comment by rieje** [comment]
No more problems now, looks fixed!

**Comment by easymodo** [comment]
nice
