### ISSUE TITLE
No release for ubuntu focal?

### ISSUE THREAD

**Issue by xaviermarchegay** [easymodo/qimgv#341]
I am using Linux Mint 20.2 and the ppa (https://launchpad.net/~easymodo/+archive/ubuntu/qimgv).

Is it normal that the recent releases (>=1.0.0) are not available on focal? Linux Mint 20.2 is still on that ubuntu release.

It is not a big deal because qimgv still works perfectly for my use but I would rather ask in case of this is a mistake.

**Comment by easymodo** [comment]
I've bumped Qt requirement to 5.14 minimum, but then found out that focal (& mint) still have 5.12. Bad decision..
I'll revert some stuff so that qimgv builds with qt 5.12, expect probably in a few days

**Comment by easymodo** [comment]
focal build is up
