### ISSUE TITLE
Settings not saved

### ISSUE THREAD

**Issue by kamiyaa** [easymodo/qimgv#349]
Not sure why this is happening but it persisted in previous versions as well (back in 0.8.0 I believe).
But qimgv's settings are being saved for some reason.
After clicking apply or save, it only works for the current session.
After quitting and opening qimgv again, it fails to remember previous configurations.

Any idea on why this is?

Running on Gentoo, Linux 5.14, sway wayland.
qimgv-1.0.2

One solution to this would be to have a config text file to read from (https://github.com/easymodo/qimgv/issues/64)
One suggestion I have is maybe considering using the [toml](https://github.com/toml-lang/toml) format as its standardized and probably has [libraries](https://marzer.github.io/tomlplusplus/) around that can parse it.

Great project btw!

**Comment by easymodo** [comment]
What? Weird, never encountered this.. 
Config file permissions are fine?  Is it modified on app exit?

Still happens if you remove `.config/qimgv`?

**Comment by kamiyaa** [comment]
Oh wait, you're right. Why is `.config/qimgv` read-only?
I removed it and its been fixed.
Sorry about that xd
