### ISSUE TITLE
Compilation errors on OpenBSD with CLang: `no template named 'auto_ptr' in namespace 'std'`

### ISSUE THREAD

**Issue by anoduck** [easymodo/qimgv#358]
After having to add an extra flag for cmake to find my qt5 library:

```bash
cmake ../ -DCMAKE_INSTALL_PREFIX=/usr/local/ -DCMAKE_INSTALL_LIBDIR=lib -DQt5_DIR=/usr/local/lib/qt5/cmake/Qt5/
```

I attempted to compile the program, which resulted in a stream of the same error repeated continuously on the command line. It references the nonexistence of a template for `auto_ptr`, and references exiv2:

```bash
In file included from /usr/local/include/exiv2/exiv2.hpp:28:
In file included from /usr/local/include/exiv2/bmffimage.hpp:27:
In file included from /usr/local/include/exiv2/image.hpp:28:
In file included from /usr/local/include/exiv2/exif.hpp:35:
/usr/local/include/exiv2/tags.hpp:143:17: error: no template named 'auto_ptr' in namespace 'std'; did you mean simply 'auto_ptr'?
        typedef std::auto_ptr<ExifKey> AutoPtr;
                ^~~~~
/usr/local/include/exiv2/config.h:105:3: note: 'auto_ptr' declared here
  using auto_ptr = std::unique_ptr<T>;
```

It appears that this error was encountered for every file the installation process attempted to compile.  In my experience, these errors usually can be negotiated by tweaking the compilation parameters. But this is out of my scope of knowledge.

**Comment by easymodo** [comment]
I'll look into it later. Could be some outdated libs openbsd or whatever

As a quick solution try `cmake -DEXIV2=OFF` (you'll only lose metadata support from cameras etc)

**Comment by anoduck** [comment]
I tried it, and ran into another issue with it not identifying OpenCV. At this point, it looks to be a pain in the butt to achieve a successful compilation. You are more than welcome to close out the issue, but if you want to troubleshoot both errors, I am willing.

**Comment by anoduck** [comment]
After disabling EXIV2, I had to next disable OPENCV_SUPPORT, because the OpenCV libraries are located in two different places on my system. The OpenCV files for cmake support are located under `/usr/local/lib/cmake/opencv4` where the OpenCV4 files needed for compilation such as the problematic `core.hpp` are located in `/usr/local/include/opencv4`. Then came the problem of attempting to compile the `linuxwatcher.cpp.o`, which failed due to the inability to locate `sys/inotify.h`, which is in `/usr/local/include/inotify/sys/inotify.h`.

Not sure if any of this helps anything, but here is where it stands.
