### ISSUE TITLE
webm not working

### ISSUE THREAD

**Issue by horusra** [easymodo/qimgv#36]
Hi, I'm running Windows 10 Enterprise

Opening a webm just gives me a black screen, regular images work fine. Does qimgv rely on windows media player? because I don't have that.

Is there a possibility to utilize MPV for webm display?

**Comment by easymodo** [comment]
I'm going to try QtAV(which uses ffmpeg) for video playback. Current implementation uses qmediaplayer which shits the bed half the time. If you want you can try installing CCCP 32 bit (webm works on my machine with that codec pack, on win 8.1)
