### ISSUE TITLE
Is it possible to control window's minwidth/minheight

### ISSUE THREAD

**Issue by Gigas002** [easymodo/qimgv#361]
I'm currently using [nomacs](https://github.com/nomacs/nomacs) and I love how it gives you an opportunity to make your window as small as it possible. I'd like to know if it's possible with qimgv too. Here's screenshot of comparison windows's minwidths of nomacs (left, barely seen) and qimgv (right):
![Screenshot_20211112_104730](https://user-images.githubusercontent.com/24297712/141430568-0c4e7e97-41b9-40d3-85cf-f605d9f98968.png)
:

Same question applies to minimal height of window.

**Comment by easymodo** [comment]
done, there's no limit now (just up to what kde allows due to window buttons)

**Comment by Gigas002** [comment]
Awesome!
