### ISSUE TITLE
Alt+Wheel doesn't differentiate WheelUp and WheelDown

### ISSUE THREAD

**Issue by eugenesvk** [easymodo/qimgv#367]
I'd like to bind some actions to <kbd>Alt</kbd><kbd>WheelUp</kbd>/<kbd>WheelDown</kbd>
It works with <kbd>Ctrl</kbd> and <kbd>Shift</kbd> just fine, however, with <kbd>Alt</kbd>:

  - the app doesn't show any Wheel button in settings, it only shows `Alt+` (for <kbd>Ctrl</kbd><kbd>WheelUp</kbd> it shows `Ctrl+WheelUp`)
  - there is no differentiation between <kbd>WheelUp</kbd>/<kbd>WheelDown</kbd>, any Wheel-action triggers this hotkey

Windows 10 21H2
qimgv v1.0.2

**Comment by easymodo** [comment]
Might be OS limitation? If input just doesnt reach qimgv

**Comment by eugenesvk** [comment]
Hm, how would I check that?
I mean, it works fine in your app without modifiers and with non-alt modifiers, and I can verify in AutoHotkey that I can rebind <kbd>Alt</kbd><kbd>WheelUp</kbd>/<kbd>WheelDown</kbd> just fine, so they are recognized by a different app, so doesn't seem like any OS limitations

**Comment by easymodo** [comment]
i'll take a look at it later today, not on windows atm

**Comment by easymodo** [comment]
fixed
