### ISSUE TITLE
APNG support

### ISSUE THREAD

**Issue by RuStAk** [easymodo/qimgv#38]
Would be nice to have APNG support. 
Most browsers now support it, no reason to not have it in an image viewer.

**Comment by Mel34** [comment]
@easymodo please correct me if I'm wrong, but my understanding is that qimgv is a wrapper for qt5 graphics libraries that do all the heavy lifting. So in order to get APNG support, you'll need qt5 to support it first. You'll probably need https://github.com/Skycoder42/qapng to do that.
If you're using Arch, it's in AUR: https://aur.archlinux.org/packages/qt5-apng-plugin/

**Comment by easymodo** [comment]
@Mel34 Yup. Tried that one sometime ago, it worked but had some issues with transparency.

**Comment by smaragdus** [comment]
I work with animated PNG images daily and for me support for APNG is essential, I hope it will be implemented in the not so distant future.

@easymodo 
I discovered **qimgv** a couple of days ago, I tested it and liked it, good work, thanks. I am glad that **qimgv** is truly portable- it does not write to AppData and to Windows Registry. I also appreciate that the users are given the option to choose between video support and no video support versions (I chose the latter).

I wrote a short introduction to **qimgv** for The Portable Freeware users- you can find it [here](https://www.portablefreeware.com/forums/viewtopic.php?f=4&t=24358). I did not find which Windows versions are supported- I supposed that **qimgv** should work on Windows 7 or newer.

I may suggest a few enhancements for the future releases of the program.

**Comment by easymodo** [comment]
@smaragdus thanks for a nice overview! 

I'll look into apng sometime soon

**Comment by easymodo** [comment]
Done in the latest release. (via Skycoder42's plugin)

**Comment by smaragdus** [comment]
@easymodo 

> Done in the latest release. (via Skycoder42's plugin)

I have just tested version [0.7.2](https://github.com/easymodo/qimgv/releases/tag/0.7.2) (portable, no video) and I can confirm that animated PNG files are played just fine, excellent job, thank you very much!
