### ISSUE TITLE
Arch Linux qimgv 1.0.2-1 - libopencv - cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by raven2cz** [easymodo/qimgv#381]
Hi, do you have a connection with FabioLolix? 

https://aur.archlinux.org/packages/qimgv/

libopencv_imgproc.so.4.5: cannot open shared object file: No such file or directory

Do you need impl modifs because new api 4.5? In actual case, qimgv doesn't work in arch. Or some downgrade will be necessary. It seems that this problem is systematic issue, 4.3, 4.4, 4.5 now. It needs some idea how to solve it in common case.

**Comment by easymodo** [comment]
reinstalling qimgv usually fixes these kinds of things i think
(so it gets linked to the new .so file after opencv update)

>Hi, do you have a connection with FabioLolix?

no

**Comment by SpezialK-dev** [comment]
I had the same problem using the qimgv-git instead of the qimgv repository fromt the Aur fixed it for me. So it seems to be a package Issue.

**Comment by raven2cz** [comment]
yes, thanks for help. qimgv-git after rebuild (do not use cache) works. I use git version now and it was build with new lib. Thanks.
