### ISSUE TITLE
[Feature request]  about scrolling the image with the mouse wheel

### ISSUE THREAD

**Issue by tchxyc** [easymodo/qimgv#384]
Hello, author of qimgv！I want to add a feature if possible.

I want scrolling the image with the mouse wheel and goto next image by mouse wheel too.

Exactly, when I reach the bottom of the picture, if I continue to scroll the mouse wheel, the software can automatically skip to the next picture.

**Comment by CrypticCus** [comment]
I think they are configurable via settings. did u check?

**Comment by tchxyc** [comment]
No, if I want scroll image with mouse wheel I need to check the 3rd option, and then wheel down can't go to next image.
![Snipaste_2022-01-05_19-52-15](https://user-images.githubusercontent.com/49787317/148213438-33b116fc-5d1d-420b-96b5-7a37f9ca0544.png)

**Comment by easymodo** [comment]
done
