### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by xiaozixun** [easymodo/qimgv#388]
I hope to add "Allow only one instance to run" setting.

Other than that have you considered making it replace the video player? Or to put it another way add more playback settings.

**Comment by easymodo** [comment]
>have you considered making it replace the video player

No, not really. This is mostly intended for playing random mp4 downloads etc

**Comment by xiaozixun** [comment]
> 
> No, not really. This is mostly intended for playing random mp4 downloads etc

So is  "Allow only one instance to run" achievable?

Please don't blame me for asking follow-up questions, as I'm not a native English speaker, so it's not clear if I'm getting the meaning in place via machine translation

**Comment by easymodo** [comment]
>So is "Allow only one instance to run" achievable?

yes, in future releases
