### ISSUE TITLE
qimgv doesn't end process when pressing ESC when compiled with qt6

### ISSUE THREAD

**Issue by kattjevfel** [easymodo/qimgv#394]
If qimgv is compiled with qt6 (like I've done in [qimgv-light](https://aur.archlinux.org/packages/qimgv-light)), when you press ESC to close the program, the window disappears but the process stays. This leads to errors when too many instances have been opened, and I also had the pleasure of ~160 qimgv re-appearing as I started KDE today, as it detected them as having been opened before shutdown.
Compiling with the exact same options but with qt6 replaced with qt5, all works well again.

Errors of too many clients:
```
katt@main ~ » Maximum number of clients reachedqt.qpa.xcb: could not connect to display :1
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.
```

OS: Arch Linux
Qt: 6.3.0beta
DE: KDE Plasma 5.24.0 Xorg
qimgv: 1.0.2 and 8b011707 tested

**Comment by kattjevfel** [comment]
Thanks for the quick fix, unfortunately it doesn't seem to help. I compiled b8d3a5f5 and it behaves just the same as before.

**Comment by easymodo** [comment]
>EDIT: nvm, it was because I compiled it in my clean chroot that uses stable repos.

Didnt see your edit, re-checked myself, definitely fixed. Not my fault by the way, blame qt ninjas for changing the way stuff works

**Comment by kattjevfel** [comment]
Aye, not blaming you.
