### ISSUE TITLE
Error when trying to open animated JXL files

### ISSUE THREAD

**Issue by Takuyax** [easymodo/qimgv#402]
Problem:
When trying to open animated JXL files, a "Load failed" message, followed by the filename is displayed. In folder view a placeholder icon is displayed for animated JXL files.

Versions:
Qimgv is version 1.0.2, just compiled from the latest source today
libjxl and qt-jpegxl-image-plugin were also compiled from the latest source today

OS: Kubuntu 21.04

How to reproduce:
1. Compile and install https://github.com/libjxl/libjxl, https://github.com/novomesk/qt-jpegxl-image-plugin and qimgv, according to instructions. (It might be necessary to reboot or re-login)
2. Open the attached logo.jxl file in qimgv to verify if the JXL plugin works
3. Qimgv should display the file correctly.
4. Open the attached Animated_PNG_example_bouncing_beach_ball.jxl
5. Qimgv will display an error message instead of displaying the file.
6. Optional: Open the Animated_PNG_example_bouncing_beach_ball.jxl in Gwenview (which also depends on libjxl and the plugin) to verify that the library and plugin handle animation correctly

[jxl-files.zip](https://github.com/easymodo/qimgv/files/8196962/jxl-files.zip)
.

**Comment by easymodo** [comment]
its disabled by default because that plugin had some memory consumption issues (could be already fixed)

`settings - advanced - check enable jxl animation`
