### ISSUE TITLE
[Bug] Opening images with qimgv from other programs fails

### ISSUE THREAD

**Issue by kin-patsu** [easymodo/qimgv#410]
Using latest alpha (1.0.3-alpha+4ccb465) on Windows 11 (21H2 build SO 22000.652), although it also happened on Windows 10 with previous versions.

Trying to open an image from an external program (example, using "Open in external program" in hydrus) results in qimgv giving the following error rather than opening the image:

"This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem. Available platform plugins are: direct2d, minimal, offscreen, webgl, windows."

**Comment by easymodo** [comment]
fixed
re-download this one https://github.com/easymodo/qimgv/releases/edit/v1.0.3-alpha
