### ISSUE TITLE
Change for Arch AUR git package

### ISSUE THREAD

**Issue by roland-rollo** [easymodo/qimgv#413]
Hi!

If you had a moment in the future, could you please update the AUR git package?
For jxl animations to work, you need to install `qt6-jpegxl-image-plugin` now (the qt5 version gives nothing after today's update). In addition, without `qt6svg`, the package does not want to build, and it does not have it as a dependency so maybe it worth to add it.

For some reason, if I search for new AUR packages it now always show as package to update, but then it says it is at the latest version and just reinstall. Maybe something with branch name or commit hush changed?

Shouldn't qimgv be built with `qt6-tools` now? Everything else working great, as always!

**Comment by easymodo** [comment]
Ok fixed the release tag & reverted to check for qt5 first (looks like some imageplugins are still not updated for qt6 in aur, so whatever lets keep qt5)

**Comment by 3xploiton3** [comment]
> Ok fixed the release tag & reverted to check for qt5 first (looks like some imageplugins are still not updated for qt6 in aur, so whatever lets keep qt5)

@easymodo please update package aur
https://aur.archlinux.org/packages/qimgv-git

thanks
