### ISSUE TITLE
Feature request: Checkered background for images with alpha channel

### ISSUE THREAD

**Issue by mojo-jojo-7** [easymodo/qimgv#417]
Is it possible to have an option to have checkered background for images with transparency? That would be amazing!

PS: This is the only image viewer I found that has support for video playback and doesn't suck. And what else, it blazing fast too! Thanks to the dev team for making this product.

**Comment by easymodo** [comment]
done
get the newest one from here https://github.com/easymodo/qimgv/releases/tag/latest-dev

![screenshot 7](https://user-images.githubusercontent.com/5484275/172379619-36324bb6-826c-4341-9b86-a5d8190dafe5.png)

**Comment by easymodo** [comment]
both fixed (i think)
build is at the same link above
