### ISSUE TITLE
The Folder View, Settings, and Close icons in the upper right corner are not displayed in Full Screen mode

### ISSUE THREAD

**Issue by erffle** [easymodo/qimgv#419]
If you select these settings:

Open in fullscreen = Yes
Thumbnail panel = Yes
Thumbnail panel position = Bottom

and move the mouse cursor to the upper right corner, the Folder View, Settings, and Close icons are not displayed, making it impossible to quickly close the Viewer with the mouse.

If you exit FullScreen mode to windowed mode and then return back to FullScreen, the Folder View, Settings, and Close icons are displayed in the upper right corner when you move your mouse to it.

**Comment by easymodo** [comment]
alright, closing the issue then :)
