### ISSUE TITLE
After latest update, Status Bar is now positioned to the right of an image file

### ISSUE THREAD

**Issue by nick-s-b** [easymodo/qimgv#422]
````
qimgv 1.0.3
qt6-5compat 6.3.1-1
qt6-base 6.3.1-1
qt6-declarative 6.3.1-1
qt6-imageformats 6.3.1-1
qt6-multimedia 6.3.1-1
qt6-svg 6.3.1-1
qt6-tools 6.3.1-1
qt6-translations 6.3.1-1
qt6-wayland 6.3.1-1

Linux ArchLinux 5.18.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 22 Jun 2022 18:10:56 +0000 x86_64 GNU/Linux
````

After I updated my whole system, I have a weird issue now... the System Bar, which used to be at the bottom, is now positioned on the right of an image. Is this a Qt issue or a `qimgv` issue?

Workaround is to disable the Status Bar in Settings but I like Status Bar...
Thanks for any guidance! 

Edit: This is what it looks like now: 
![Screenshot at 2022-06-27 00-24-31](https://user-images.githubusercontent.com/7957590/175860175-71c7dac7-218b-425e-a7d9-6085517b2740.jpg)

**Comment by easymodo** [comment]
lol
fixed

i've added an option to put thumbs bar at the side, and messed up with layouts in the process..

**Comment by nick-s-b** [comment]
@easymodo Thank you! Hope you're staying safe bro!
