### ISSUE TITLE
missing dependencies in qimgv-x64_v1.0.3-alpha-74-gef3f8258.7z

### ISSUE THREAD

**Issue by novomesk** [easymodo/qimgv#435]
Hello,

I tried `latest-dev/qimgv-x64_v1.0.3-alpha-74-gef3f8258.7z` and observed that AVIF is not working there.

Problem is that libavif.dll from MSYS2 added new dependencies: `libSvtAv1Enc.dll` and `libyuv.dll`

When I added those two, AVIF started to work.

**Comment by easymodo** [comment]
thanks, release updated
