### ISSUE TITLE
[HELP] ERROR: no opengl support set

### ISSUE THREAD

**Issue by kuwakuwi1** [easymodo/qimgv#452]
Hi @easymodo, I love your program, it's awesome.

I'm trying to modify the program myself in QtCreator , and that error shows up. 

I'm on Ubuntu 22.04, 
build using Qt 6.2.4. 
I've installed all of the required dependencies mentioned in build from source guide.

At first, the program can't locate the player_mpv.so because weirdly, it produces the file in different folder ({buildfolder}/plugins/player_mpv/player_mpv.so) instead of ({buildfolder}/lib/qimgv/player_mpv.so),

the error is like the following:
```
Could not find "player_mpv.so" in the following directories: QList("/media/candra/SSD_EXT/coding/cpp/build-qimgv-Qt_6_2_4_GCC_64bit_797c97-MinSizeRel/lib/qimgv", "/usr/lib/qimgv", "/usr/lib64/qimgv")
```

So, I changed the videoplayerinitproxy.cpp to include the ({buildfolder}/plugins/player_mpv/player_mpv.so) folder.

I build the program again, the error gone away, but new error shows up, and the video player didn't even load.
The error:
```
virtual void QPlatformBackingStore::composeAndFlush(QWindow*, const QRegion&, const QPoint&, QPlatformTextureList*, bool) no opengl support set
```

Could you assist me with this error? I guess it's related to the Qt version? or the mpv version?

My current mpv version:
```
$: mpv --version
mpv 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: 4.4.2-0ubuntu0.22.04.1
```

Thank you in advance.

**Comment by easymodo** [comment]
Hi

>I guess it's related to the Qt version? 

yes it's related to qt6, grab this one

`apt install qtbase5-dev qtbase5-dev-tools libqt5svg5-dev qttools5-dev`       (qttools5-dev was missing in wiki page, just updated it)

Then delete build folder & reopen the project in qtcreator. It should now use qt5. Just did this on 22.04 vm, videoplayer works

also, instead of this

>So, I changed the videoplayerinitproxy.cpp to include the ({buildfolder}/plugins/player_mpv/player_mpv.so) folder.

just copy `player_mpv.so` to `/usr/lib/qimgv/`

**Comment by kuwakuwi1** [comment]
Hi, thanks for responding

I got it working by downgrading Qt version to Qt 5.15.2.
