### ISSUE TITLE
Won't play AV1 video

### ISSUE THREAD

**Issue by tomasklaen** [easymodo/qimgv#453]
Even when I replace the mpv binary with a new one that plays AV1 fine, qimgv still displays just a black screen.

Here's a test video file: [stock_cliff.mp4](https://user-images.githubusercontent.com/47283320/211365186-678a1934-8e60-4cc6-9076-77aad06dbee2.mp4)

OS: Win 10
qimgv: 1.0.3

**Comment by easymodo** [comment]
Replacing exe wont to the trick, you need to recompile with new libmpv.dll

I just did a build, take the latest one here (with `-video`)

https://github.com/easymodo/qimgv/releases/tag/latest-dev

**Comment by tomasklaen** [comment]
Thx! That works :)
