### ISSUE TITLE
Doesn't work with opencv 4.7.0?

### ISSUE THREAD

**Issue by taprobane99** [easymodo/qimgv#461]
i am running manjaro/arch and just updated to latest stable with opencv 4.7.0

now i get

qimgv: error while loading shared libraries: libopencv_imgproc.so.406: cannot open shared object file: No such file or directory

and qimgv won't open

**Comment by easymodo** [comment]
reinstall from AUR

**Comment by taprobane99** [comment]
worked fine on an intel desktop

hangs at 99% on my amd laptop (both qimgv and qimgv-git)

any clues?

**Comment by taprobane99** [comment]
hi this now works on my computer so closing.
