### ISSUE TITLE
Compiling on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by salvadhor** [easymodo/qimgv#47]
I'm getting following error while compiling qimgv on 16.04:

[ 69%] Building CXX object gui/viewers/CMakeFiles/viewers.dir/mpvwidget.cpp.o
cd /build/qimgv-0.6/obj-x86_64-linux-gnu/gui/viewers && /usr/bin/x86_64-linux-gnu-g++   -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I/build/qimgv-0.6/obj-x86_64-linux-gnu/gui/viewers -I/build/qimgv-0.6/gui/viewers -I/build/qimgv-0.6 -I/build/qimgv-0.6/res -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -fPIC -fPIC -std=c++11 -O3 -DNDEBUG   -fPIC -o CMakeFiles/viewers.dir/mpvwidget.cpp.o -c /build/qimgv-0.6/gui/viewers/mpvwidget.cpp
/build/qimgv-0.6/gui/viewers/mpvwidget.cpp: In member function 'void MpvWidget::command(const QVariant&)':
/build/qimgv-0.6/gui/viewers/mpvwidget.cpp:62:5: error: 'command' is not a member of 'mpv::qt'
     mpv::qt::command(mpv, params);
     ^
/build/qimgv-0.6/gui/viewers/mpvwidget.cpp: In member function 'void MpvWidget::setProperty(const QString&, const QVariant&)':
/build/qimgv-0.6/gui/viewers/mpvwidget.cpp:66:5: error: 'set_property' is not a member of 'mpv::qt'
     mpv::qt::set_property(mpv, name, value);
     ^
/build/qimgv-0.6/gui/viewers/mpvwidget.cpp: In member function 'QVariant MpvWidget::getProperty(const QString&) const':
/build/qimgv-0.6/gui/viewers/mpvwidget.cpp:70:12: error: 'get_property' is not a member of 'mpv::qt'
     return mpv::qt::get_property(mpv, name);

**Comment by easymodo** [comment]
1. libmpv-dev from 16.04 is too old, get the one from this repo:
http://tipsonubuntu.com/2017/02/16/install-mpv-media-player-0-24-ubuntu-16-04-16-10/
2. Qt is also too old, we need 5.6. Easily fixable though. Comment out this one line in main.cpp:
```
//QGuiApplication::setAttribute(Qt::AA_DisableHighDpiScaling);
```
Then it should build

**Comment by salvadhor** [comment]
Thanks for explanation :)
