### ISSUE TITLE
Compiling on Fedora - New Dependencies

### ISSUE THREAD

**Issue by stankovictab** [easymodo/qimgv#472]
`qt5` and `qt5-devel` as mentioned in the wiki are no longer available. 
Instead, packages `qt5-qtbase`, `qt5-qtbase-devel`, `qt5-qtsvg`, `qt5-qtsvg-devel` and `qt5-linguist` are needed. 
Also, the following command from the wiki doesn't work in the `fish` shell, might be better to outline that, or even change it so that it's universal for all shells. 
```
make -j`nproc --ignore=1`
```

**Comment by easymodo** [comment]
thank you, wiki page updated
