### ISSUE TITLE
mp4 support

### ISSUE THREAD

**Issue by CorePoint** [easymodo/qimgv#48]
Hey, would you mind adding mp4 support, should be no problem as you use mpv for the webm/gif support anyway right?

Thank you for creating this application, i appreciate it! :)

**Comment by easymodo** [comment]
> should be no problem as you use mpv 
Yeah. I'll make a checkbox for some video formats, as well as maybe filesize limit

**Comment by CorePoint** [comment]
That sounds like a very good idea, I'm looking forward to it.

Thank you!

**Comment by easymodo** [comment]
Done (without size limit atm, need to think how to do it without affecting startup speed).
