### ISSUE TITLE
Compilation failed with new exiv2 version

### ISSUE THREAD

**Issue by DigitalDragon64** [easymodo/qimgv#481]
exiv2 has removed AnyError, which is still used in qimgv/sourcecontainers/documentinfo.cpp. Current compilation on Arch Linux via yay from the AUR fails because of following error:

/home/$USER/qimgv/qimgv/sourcecontainers/documentinfo.cpp:272:19: error: ‘AnyError’ in namespace ‘Exiv2’ does not name a type
  272 |     catch (Exiv2::AnyError& e) {
      |                   ^~~~~~~~

**Comment by DigitalDragon64** [comment]
Replace Exiv2::AnyError with Exiv2::Error seems to solve the problem. If I'm seeing this correctly, it was only a name change for exiv2, so this should be the ideal solution.

**Comment by DigitalDragon64** [comment]
#482 Added a pull request, which should solve the issue

**Comment by easymodo** [comment]
merged

**Comment by DigitalDragon64** [comment]
Pull request fixed the issue
