### ISSUE TITLE
WebM/MP4 playback issues

### ISSUE THREAD

**Issue by Web-eWorks** [easymodo/qimgv#49]
Using Solus Linux / qimgv master, attempting to playback video files fails without the MPV executable installed. If this is intended, I recommend adding `mpv` to the list of dependencies in the README.

When MPV is installed, the file plays very small (~1/4 size) in the lower-left hand corner of the screen and without zoom, though it does scale somewhat when entering fullscreen.

**Comment by Web-eWorks** [comment]
Update: the sizing issue is resolved when setting `QT_AUTO_SCREEN_SCALE_FACTOR=0` before running `qimgv`. As I want auto scaling off (due to issues with UI scaling in qimgv, VLC et. al.), this is fine, but you may want to look into properly scaling the video player with DPI changes.

**Comment by easymodo** [comment]
Thanks for reporting.
Just got the mpv scaling to [work correctly.](https://www.youtube.com/watch?v=E_BR2od9Ul0)
Also i've now hardcoded the `QT_AUTO_SCREEN_SCALE_FACTOR=0`. If you want to scale the UI use this:  `QT_SCALE_FACTOR=x.x` 
I'll put up a release tomorrow
