### ISSUE TITLE
native wayland support

### ISSUE THREAD

**Issue by Gigas002** [easymodo/qimgv#490]
I know you're being very busy lately and also I understand, that this feature requires a lot of work. Just wondering if it is planned in some distant future.
The app does work on wayland through `xwayland`, yes, but it's a bit buggy, comparing to `x11` session

**Comment by 00-kat** [comment]
This can probably be closed now since it seems to run on Wayland now, at least for me.

**Comment by Gigas002** [comment]
Indeed, qt6 version works with Wayland natively, as it seems
