### ISSUE TITLE
Some issues with files

### ISSUE THREAD

**Issue by Web-eWorks** [easymodo/qimgv#50]
Just a couple of improvements / bugs:
- qimgv will not detect images without an extension in folders - consider using libmagic to determine type of files?
- Periodically (on image change?) rescan image folder for changes - currently does not pick up new files / deleted files / changes to files in the same folder.

**Comment by linxon** [comment]
bump

**Comment by easymodo** [comment]
File tracking done (for linux)

I'll do a release once some other stuff is fixed
