### ISSUE TITLE
Crash on reading this svg file

### ISSUE THREAD

**Issue by God-damnit-all** [easymodo/qimgv#502]
I downloaded this svg file from Discord, qimgv crashes upon trying to read it:

[549e0b9954236583f841032b85ba45f9.svg](https://github.com/easymodo/qimgv/assets/53661808/ed5044c0-f215-48e7-8b00-a8753afd4258)

**Comment by easymodo** [comment]
old version?

I can't reproduce it on [1.0.3](https://github.com/easymodo/qimgv/releases/tag/latest-dev)

**Comment by zymelaii** [comment]
> Just compiled from the latest commit [e012f04](https://github.com/easymodo/qimgv/commit/e012f04845ba3baac6afefa24ccbfab90ae70810) and it's still an issue on there too.

with env
- Windows 10
- without OpenCV
- without MPV
- without EXIV2
- commit on e012f04

it works well on my machine, maybe 3rdparty are to blame or have you mistaken something?
