### ISSUE TITLE
Mirror images?

### ISSUE THREAD

**Issue by gbl** [easymodo/qimgv#51]
First: great viewer, exactly what I need to browse a directory of images, make some minor changes. and save them back without much hassle.

My usecase? I have cupboard full of 20+ year old slides, finally got a slide scanner, and after that thing drops a few hundred images into some directory, i need to scroll through them quickly and possibly rotate them. And if I insert a slide the wrong way, I need to flip/mirror it as well.

However - It doesn't seem like mirroring is in the GUI somewhere. utils/imagelib.cpp has flipH and flipV methods, so I guess this should be easy; but those methods don't seem to be called from anywhere. Could you please add this to a future version?

-----------------------------------------

On a side note, the current version doesn't compile on Ubuntu 16.04, since that comes with qt 5.5.1, and qimgv seems to need qt5.6. A few patches here and there fix this, at the expense of high dpi scaling and device pixel ratios. Could you try to detect these in the configure script, and possibly use some #ifdef-s to not use these features on qt 5.5? 16.04 is the current Ubuntu Long Term release, and probably won't go away for a while even when the next LTS (18.04) comes out, so there will probably a good amount of people who appreciate that. Thanks!

**Comment by easymodo** [comment]
Just pushed a new release, you can now mirror images with H/V keys.
______________

> 16.04 is the current Ubuntu Long Term release, and probably won't go away for a while 

That's a valid argument, I'll try to do something about qt 5.5.
