### ISSUE TITLE
libmpv / mpv support with portable build?

### ISSUE THREAD

**Issue by Hrxn** [easymodo/qimgv#52]
Hey...

I've been testing this one here for a while: `qimgv64-portable-0.6.2.exe` (on Windows 10 x64 FCU).

First of all, I really like the program so far.
Nice minimalist design, very fast and responsive. Kudos to you 😄 .

Just a quick question:
In the settings menu there are options to choose a path for a mpv binary, but all these options are greyed out / deactivated. Is this intentional? Or do I have to set a specific property in the config?

**Comment by easymodo** [comment]
Yes, that is intentional. I left out mpv to reduce filesize (because it already starts kinda slow on windows). 
Just use regular installer if you want video support.

**Comment by Hrxn** [comment]
> [..] because it already starts kinda slow on windows [..]

Interesting, why is that? Because qimgv can use the system-wide installation of Qt on Linuxes?

From my experience (Windows 10 installed on SSD - of course - and qimgv starting from SSD as well) I can only say that program startup is pretty fast right now. Near instantaneous, basically.
To be honest, I would not my if it started a bit slower. I care about performance, no doubt, but program startup time is not so much a priority, definitely not as important as performance during operation. That is, displaying images fast, and especially the preview images in the overview. That is where most image viewers lack, in my opinion.

**Comment by easymodo** [comment]
> Because qimgv can use the system-wide installation of Qt on Linuxes?
Yeah, it's Qt. Try launching something like jpegview on windows, it starts noticeably faster, even on ssd.

**Comment by easymodo** [comment]
There is now a portable build with mpv

**Comment by Hrxn** [comment]
Thank you very much, I really appreciate it!
