### ISSUE TITLE
The application crashes when trying to view some JXL files

### ISSUE THREAD

**Issue by torinx** [easymodo/qimgv#527]
When I look exif data of images makes app crash with exiftool they all have "JXL Codestream" as their file type.
Note: It happens on alpha ~~84 and~~ 101.

Example image:
[red-roses.jpeg_upscayl_4x_remacri.zip](https://github.com/easymodo/qimgv/files/13710339/red-roses.jpeg_upscayl_4x_remacri.zip)

**Comment by easymodo** [comment]
fixed in `102`

https://github.com/easymodo/qimgv/releases/tag/latest-dev
