### ISSUE TITLE
Sort order

### ISSUE THREAD

**Issue by denzerdhard** [easymodo/qimgv#53]
I think that an important feature is missing - ability to sort image list by mtime, file size etc.

**Comment by easymodo** [comment]
coming in v0.7

**Comment by rieje** [comment]
Where is this option? I can't seem to find it.

**Comment by easymodo** [comment]
![sorting](https://user-images.githubusercontent.com/5484275/95613020-f3ebe180-0a6c-11eb-9f96-e0e2d54c198f.jpg)

**Comment by easymodo** [comment]
you can also assign shortcuts to different sort modes. tapping twice reverses the order
