### ISSUE TITLE
[Feature] German translation

### ISSUE THREAD

**Issue by Auravendill** [easymodo/qimgv#530]
[de_DE.ts.zip](https://github.com/easymodo/qimgv/files/13804574/de_DE.ts.zip)

Hello, I made a German translation. Sorry, that I took so long after asking how to create one. #79 
Github doesn't allow .ts files in issues btw, so I put it into a zip. I hope this is fine.

Happy new year!

**Comment by easymodo** [comment]
Very nice, thank you and happy new year!

Added in [v1.0.3-alpha-104](https://github.com/easymodo/qimgv/releases/tag/latest-dev)
