### ISSUE TITLE
How do I designate a quick folder?

### ISSUE THREAD

**Issue by ob1024** [easymodo/qimgv#532]
How do I designate a quick folder?

**Comment by easymodo** [comment]
click the folder icon

**Comment by ob1024** [comment]
![제목 없음](https://github.com/easymodo/qimgv/assets/65034416/b35491f5-6e03-4e4f-8350-594ce2bfb744)
I want to change the folder here... ㅜ-ㅜ, there are 9 folders that are all the same

**Comment by ob1024** [comment]
> click the folder icon
![제목 없음](https://github.com/easymodo/qimgv/assets/65034416/741dd280-5bb2-4d47-9b5a-cf4bd116d605)



> 폴더 아이콘을 클릭합니다.

I want to change the folder here... ㅜ-ㅜ, there are 9 folders that are all the same[](url)
