### ISSUE TITLE
Some keystroke detection is broken [Qt 6.7.0]

### ISSUE THREAD

**Issue by eddiezato** [easymodo/qimgv#539]
Specifically these keys are not detected by qimgv:
- left arrow
- right arrow
- up arrow
- down arrow
- pgup
- pgdown
- home
- end
- etc

Win 11, latest qimgv-master, Qt 6.7.0, msys2/ucrt64

**Comment by eddiezato** [comment]
Had to change the keycodes for the problem buttons here:
https://github.com/easymodo/qimgv/blob/52f482b6451d24b4b7f4fe2ca763b0be9d24c4c1/qimgv/utils/inputmap.cpp#L28
```cpp
keyMap.insert( 57426 , "Ins" );
keyMap.insert( 57415 , "Home" );
keyMap.insert( 57417 , "PgUp" );
keyMap.insert( 57427 , "Del" );
keyMap.insert( 57423 , "End" );
keyMap.insert( 57425 , "PgDown" );
keyMap.insert( 57416 , "Up" );
keyMap.insert( 57437 , "Menu" );
keyMap.insert( 57419 , "Left" );
keyMap.insert( 57424 , "Down" );
keyMap.insert( 57421 , "Right" );
// numpad
keyMap.insert( 57413 , "NumLock" );
keyMap.insert( 57397 , "/" );
keyMap.insert( 57372 , "Enter" );
```
Dunno why they suddenly stopped working.

**Comment by easymodo** [comment]
that's weird, idk why they had to change the codes

qt 6.7 on linux does not have this issue

**Comment by eddiezato** [comment]
What bothers me is, did they really change these codes for win? Or is it just some local issue on my system?

**Comment by easymodo** [comment]
Okay there is indeed an issue ( `mingw64/mingw-w64-x86_64-qt6-base 6.7.0-1` )

No idea why they had to change them. Maybe some bug
