### ISSUE TITLE
Image rotation data from exif is not taken into account

### ISSUE THREAD

**Issue by nick-s-b** [easymodo/qimgv#54]
Hi,

Quite often I notice that the image orientation of most of the images that I take with my phone is wrong when viewed with qimgv. I've narrowed it down to image orientation metadata. Apparently, most phones encode the image off a sensor in the same orientation and then they just encode the orientation into the exif.

Example pic: https://my.mixtape.moe/prbxhn.jpg

Pic above will look properly oriented in all web browsers and most viewers but not with qimgv.  It contains `Rotate 270 CW` as `Orientation` parameter.

http://leancrew.com/all-this/2009/04/derotating-jpegs-with-exiftool/
https://sno.phy.queensu.ca/~phil/exiftool/exiftool_pod.html

**Comment by easymodo** [comment]
Thanks for reporting!

Just fixed it in dev branch (via Exiv2 lib).
