### ISSUE TITLE
Video playback detaches on mpv v0.38.0

### ISSUE THREAD

**Issue by Stoppedpuma** [easymodo/qimgv#541]
Videos will detach from the window when using mpv v0.38.0, It works as intended on v0.37.0. The video will still playback normally but the video window cannot be closed or interact with keybinds, only the main window can. The video window can be closed if the main window is closed though.

Screenshot showcasing this issue (Top is the main window, below is the video window that detached):

![1714287451-2](https://github.com/easymodo/qimgv/assets/58333920/3ae50c0d-a703-4e25-97ad-72fd0dfd742d)

**Comment by easymodo** [comment]
could you please try the latest commit, does this fix the issue?

**Comment by Bedz01** [comment]
> could you please try the latest commit, does this fix the issue?

That fixed it! Thank you :)
