### ISSUE TITLE
[Feature Request] Use `=` instead of `+` as default keybind for zooming

### ISSUE THREAD

**Issue by 00-kat** [easymodo/qimgv#546]
I would send a PR, but I can't find where the config file is stored.

You zoom out with `-`. You zoom in with `+` i.e. `Shift+=`. So if you want to zoom in and out quickly, you have to toggle holding shift. I know it can be changed easily in the config, but I'm asking for a change to the *default* since I don't think the current default makes much sense.

The only people this would affect is people who zoom with a number pad, but I'm not sure how many people do that, so I can't say whether this issue is a good idea or not.

**Comment by spenserblack** [comment]
Just to offer some context, the way Chrome works:
- <kbd>ctrl</kbd> + <kbd>+/=</kbd>: zoom in
- <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>+/=</kbd>: zoom in
- <kbd>ctrl</kbd> + <kbd>+</kbd> (numpad): zoom in

So it looks like there's a precedent to use an "unshifted +", aka "=", to zoom in.

**Comment by easymodo** [comment]
I think this should make sense

__zoomIn__
`+` (numpad)
`=` (number row)
`Ctrl+` (numpad)
`Ctrl=` (number row)

__zoomOut__
`-`
`Ctrl-`
