### ISSUE TITLE
Broken with opencv 4.10

### ISSUE THREAD

**Issue by Stoppedpuma** [easymodo/qimgv#549]
qimgv: error while loading shared libraries: libopencv_imgproc.so.409: cannot open shared object file: No such file or directory

**Comment by Swexti** [comment]
```
# ln -s /usr/lib/libopencv_imgproc.so.410 /usr/lib/libopencv_imgproc.so.408
# ln -s /usr/lib/libopencv_core.so.410 /usr/lib/libopencv_core.so.408
```
It was so.408 in my case, so that's what I've written. You can edit it to so.409 instead.

**Comment by easymodo** [comment]
or just rebuild qimgv, it should link with the new .so file

**Comment by Swexti** [comment]
> or just rebuild qimgv, it should link with the new .so file

yeah that's probably the better way to go about things

**Comment by Stoppedpuma** [comment]
> or just rebuild qimgv, it should link with the new .so file

Completely forgot about that, thanks!
