### ISSUE TITLE
Video controls

### ISSUE THREAD

**Issue by LemonadeCellar** [easymodo/qimgv#55]
In qimgv 0.6.3 on Windows, videos just play looped over and over. It'd be nice to have some basic controls, like a progress bar, play/pause, skip forwards and backwards (as buttons on screen and/or keyboard shortcuts).

**Comment by Hrxn** [comment]
Well, the primary purpose of qimgv is short, soundless WebMs, animated image style..
So this is probably a bit out of scope..

**Comment by LemonadeCellar** [comment]
Yup, that looks good. I'm not really sure about defaults, maybe Z/X or something like that. Thank you for responding!
