### ISSUE TITLE
Have `--help` text

### ISSUE THREAD

**Issue by MachFour** [easymodo/qimgv#56]
It would be really nice to have a bit of help text when you run `qimgv --help` at a command line, since that's what I - and I feel like others - do with programs that they don't use often and forget how to use.  Even though it's not intended for command line use, it's certainly much more helpful to have that than to just launch the program and display an error saying that there is no file called '--help'. 

Even literally copy-pasting the "Default control scheme" from the README.md would be perfect, since there's also no man page or anything :)

**Comment by easymodo** [comment]
It now outputs some info just like any other program.

Not the shortcut list though, for that i'll add some gui window (like a cheat sheet)
