### ISSUE TITLE
Removing or increasing memory limitations: "Rejecting image as it exceeds the current allocation limit"

### ISSUE THREAD

**Issue by nick-s-b** [easymodo/qimgv#561]
Hi all,
I have a bunch of high-resolution jpeg images which were probably stitched together from tiles and I can't seem to open most of them because of their size. The error that always shows up is:

`qt.gui.imageio: QImageIOHandler: Rejecting image as it exceeds the current allocation limit of 1024 megabytes`

Typical image files are of this size:
````
$ file '/tmp/art-stitch-final.jpg'
/tmp/art-stitch-final.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=7, orientation=upper-left, xresolution=98, yresolution=106, resolutionunit=2, software=GIMP, datetime=2022:11:07 20:31:39], progressive, precision 8, 22803x18584, components 3
````

The limitation seems to come from: 

https://github.com/easymodo/qimgv/blob/82e6b7537002b86b4ab20954aab5bf0db7c25752/qimgv/settings.h#L282C5-L283C48

What's the proper way to increase this limit? I have plenty of RAM so I'd like to remove some of the limitations.
Thank you!

**Comment by eddiezato** [comment]
You can increase the limit here, but no more than 8192:

![image](https://github.com/user-attachments/assets/eb4d1f53-74c8-4215-ac55-ebb8fadf3e6e)

**Comment by nick-s-b** [comment]
Thank you @eddiezato !!!! I completely missed this option!
