### ISSUE TITLE
Windows Defender Threat Detected

### ISSUE THREAD

**Issue by soul4feels** [easymodo/qimgv#566]
qimgv-x64_v1.0.3-alpha-128-gaeccf866

This auto build has a virus detected.
![Screenshot 2024-10-11 020907](https://github.com/user-attachments/assets/1632ac3a-de8a-42c9-a674-951160852cd1)

**Comment by easymodo** [comment]
Uuuh wait what? I just did a defender scan, and even threw it into virustotal, nothing  

can you check the md5 of your qimgv.exe please?  [checker tool](https://emn178.github.io/online-tools/md5_checksum.html)

qimgv-x64_v1.0.3-alpha-128-gaeccf866 / qimgv.exe   should be  `df12862a2ec1e5ae877ac76165b231b1`

**Comment by easymodo** [comment]
>Win32/Bearfoos.A!ml

`!ml` is machine learning. False positive. Google it, lots of people with the same issues

**Comment by soul4feels** [comment]
Oh, alright. That's good to know.
