### ISSUE TITLE
[Unnecessary features request] ;)

### ISSUE THREAD

**Issue by blackICE19240** [easymodo/qimgv#61]
-I'd find it useful to have a different color of background in and out of full-screen
-The ability to lock to common aspect ratios when cropping would be useful, e.g. Free, Original, 1:1, 16:9 and 18:9 (And although not necessary due to being able to rotate outside of crop, maybe a rotation button here too for the portrait equivalents)
- A proper name, one that will intrigue into trying this BUT NOTHING CHEESY! 

Again though, this is by far the best image viewer I've used and I'm just trying to find things to suggest.
I love it.

**Comment by easymodo** [comment]
Done some improvements to the crop UI. As well as background settings. Check the latest release

>A proper name, one that will intrigue into trying this BUT NOTHING CHEESY!

I'll think about it :P

**Comment by blackICE19240** [comment]
Thanks a lot, locking aspect ratios when cropping is extremely useful!
