### ISSUE TITLE
Build issue - error: call to deleted constructor of 'QImageReader'

### ISSUE THREAD

**Issue by AngryPenguinPL** [easymodo/qimgv#63]
Hi.

Trying import qimgv into OpenMandriva repository but I got a building error.

> CMakeFiles/qimgv.dir/utils/imagefactory.cpp.o -c /builddir/build/BUILD/qimgv-0.7.1/utils/imagefactory.cpp
> DEBUG util.py:498:  BUILDSTDERR: /builddir/build/BUILD/qimgv-0.7.1/sourcecontainers/documentinfo.cpp:110:49: error: call to deleted constructor of 'QImageReader'
> DEBUG util.py:498:  BUILDSTDERR:     const QImageReader& reader = (mExtension) ? QImageReader(path, mExtension) : QImageReader(path);
> DEBUG util.py:498:  BUILDSTDERR:                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> DEBUG util.py:498:  BUILDSTDERR: /usr/include/qt5/QtGui/qimagereader.h:149:20: note: 'QImageReader' has been explicitly marked deleted here
> DEBUG util.py:498:  BUILDSTDERR:     Q_DISABLE_COPY(QImageReader)
> DEBUG util.py:498:  BUILDSTDERR:                    ^
> DEBUG util.py:498:  BUILDSTDERR: 1 error generated.

Full build log here: https://paste.ubuntu.com/p/HgsqpfK2PW/

Building on OpenMandriva Cooker, qt5.11.
Any idea?

**Comment by easymodo** [comment]
Interesting, i've missed this because i use gcc not clang.

Anyway, pushed a fix to master, please try again. I even can put out a minor release if you wish.

**Comment by AngryPenguinPL** [comment]
Hi.
Thanks for fix. Build process now reach 100% :)

New minor release? Do what you want. I will adapt, no matter for me. I can use new release or just patch current.

Anyway, thanks for fix.
