### ISSUE TITLE
Panel Position Option not working

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [easymodo/qimgv#65]
If I change the Panel Position in the settings menu to bottom it is still at the top. Removing all config files or reinstalling qimgv does not solve the issue.

Software I used:

- qimgv git from today
- qt 5.12
- Gnome 3.30.2

**Comment by easymodo** [comment]
Thanks for reporting. This should be fixed now, please test

**Comment by Sebastian-Hirsch** [comment]
Thanks, its basically fixed now. Now i only have the problem, that if the mouse cursor is at the bottom edge of the screen and as much down as possible, the panel disappears. If i move the mouse cursor 1 pixel higher, it reappears. It happens only on a maximized qimgv window. The Video should show the issue. Watch the bottom of the clip and watch the mouse cursor. I dont know if this is a problem of qimgv or my desktop.
https://mega.nz/#!2SAxXI7K!bHBNjZnyTENkwD4mPpgtdNaKIw8HhbmSlm7mpP0LuZg

**Comment by easymodo** [comment]
Strange, that does not happen for me. Are you using HiDPI scaling? high res screen?

**Comment by Sebastian-Hirsch** [comment]
Yes, I am using two HiDPI Monitors (3840*2160, 24 inch each)  with a scaling factor of two set in the gnome settings menu.

**Comment by easymodo** [comment]
Fixed.

There is still an issue when buttons are not being hovered on the screen edges (qt bug?). I'll look into it later.

**Comment by Sebastian-Hirsch** [comment]
Awesome, I will test it out later today.

Am 03.01.2019 18:00 schrieb "easymodo" <notifications@github.com>:

Fixed.

There is still an issue when buttons are not being hovered on the screen
edges (qt bug?). I'll look into it later.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/easymodo/qimgv/issues/65#issuecomment-451207292>, or mute
the thread

**Comment by Sebastian-Hirsch** [comment]
I can confirm that it is fixed. I will close the issue.
