### ISSUE TITLE
Compiling on Xubuntu 18.04

### ISSUE THREAD

**Issue by TheMadSword** [easymodo/qimgv#70]
Hi,

when compiling on Xubuntu (Ubuntu) 18.04, I get the following message when compiling (at step 2a) : 

~/Builds/qimgv/build$ cmake -DCMAKE_INSTALL_PREFIX=/usr/ -DCMAKE_BINARY_DIR=${DIR}/ .. && make -j4
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/red/Builds/qimgv/build
Scanning dependencies of target qimgv_autogen
[  1%] Automatic MOC and UIC for target qimgv
[  1%] Built target qimgv_autogen
[  2%] Generating qrc_resources.cpp
Scanning dependencies of target qimgv
[  3%] Building CXX object CMakeFiles/qimgv.dir/appversion.cpp.o
[  4%] Building CXX object CMakeFiles/qimgv.dir/core.cpp.o
[...]
[ 87%] Building CXX object CMakeFiles/qimgv.dir/gui/panels/sidepanel/sidepanel.cpp.o
/home/red/Builds/qimgv/gui/panels/croppanel/croppanel.cpp: In member function ‘void CropPanel::onAspectRatioSelected()’:
/home/red/Builds/qimgv/gui/panels/croppanel/croppanel.cpp:103:44: error: ‘screenAt’ is not a member of ‘QGuiApplication’
         QScreen* screen = QGuiApplication::screenAt(mapToGlobal(ui->ARcomboBox->geometry().topLeft()));
                                            ^~~~~~~~
CMakeFiles/qimgv.dir/build.make:1959: recipe for target 'CMakeFiles/qimgv.dir/gui/panels/croppanel/croppanel.cpp.o' failed
make[2]: *** [CMakeFiles/qimgv.dir/gui/panels/croppanel/croppanel.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/qimgv.dir/all' failed
make[1]: *** [CMakeFiles/qimgv.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Any idea what the problem might be ?

Thank you !

**Comment by easymodo** [comment]
Looks like I accidentally broke the compatibility with older Qt. Fix incoming

**Comment by easymodo** [comment]
Done
```
make clean && git pull
```

then proceed to build and install
