### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by ongots** [easymodo/qimgv#71]
Не хватает выпадающей панели задач и кнопки свернуть.
Надпись сверху слишком яркая, нужна настройка цвета.
Не показывать уведомление об удалении файла.
Добавить миниатюры видео.
Добавить в контекстное меню: «Открыть папку с файлом» (Открывается папка с выделенным файлом), Копировать (Чтобы потом вставить в документ или сообщение).

**Comment by easymodo** [comment]
Пара вопросов

>Не хватает выпадающей панели задач и кнопки свернуть.

Что имеется в виду? Панельки по типу FSViewer?

>Надпись сверху 

Имена файлов? Сделаю темнее. А вообще в 0.8 будет поддержка настраиваемых тем.

>Добавить миниатюры видео.

У меня превью работают, проверьте чтобы в настройках (Advanced > Mpv binary) чтобы был указан путь к `mpv.exe`

**Comment by ongots** [comment]
> Что имеется в виду?
Панель задач Windows - чтобы переключаться между программами. FastStone Image Viewer позволяет переключаться не выходя из полноэкранного режима.
> Превью
Проверил, видео воспроизводится, а превью не отображается
![2019-02-01_095918](https://user-images.githubusercontent.com/43604031/52110132-58a03900-2608-11e9-95ed-f1cfdd6e6eed.png)

**Comment by easymodo** [comment]
>При запуске инсталлятора вылазит ошибка

Погуглил, все ругаются на антивирус (в частности avast)

>Проверил, видео воспроизводится, а превью не отображается

Исправлено в последнем релизе (была проблема с правами на запись в program files).

https://github.com/easymodo/qimgv/releases/tag/v0.7.3

**Comment by ongots** [comment]
У меня avast, после отключения ошибка не появилась.

Только-что открытая картинка не открывается повторно при клике на превью в галерее.

Интерфейс все еще ломается иногда при попытке выбора папки
![2019-02-01_141330](https://user-images.githubusercontent.com/43604031/52122431-a9755900-262b-11e9-913f-cef8cd6336db.png)

Странные комбинации клавиш для зума у вас. Удобней и логичней: 0, -, +. Нехватает отрицательного зума.

Некоторые файлы не удаляются, а вместо перемещения такие файлы копируются. Это было с некоторыми webm или webp скачанными как jpg. Для примера:
[3ur1tr7kzdc21.zip](https://github.com/easymodo/qimgv/files/2821499/3ur1tr7kzdc21.zip)

Добавить хоткеи moveto1, moveto2, moveto3, … Чтобы перемещать файлы нажатием одной кнопки, без вызова меню.

Добавить хоткей открывающий картинку в 100% разрешении с одновременной возможностью перемещения по ней. При отпускании кнопки картинка возвращалась в адаптивный размер. Короче скопировать действия LKM FastStone.

При запуске программы автоматически открывать окно выбора папки. Кстати, вы не планируете файловый менеджер как в FastStone Image Viewer? Очень удобно выделять по несколько файлов и перетаскивать в папки слева. Особенно когда теперь есть такой офигенный зум в галерее. Ну и вообще перемещаться по папкам как человек.

**Comment by easymodo** [comment]
>файловый менеджер

Да, собирался делать. Только много придется переписывать. Будет что-то вроде дерева как в фастстоне, либо же breadcrumb меню сверху, еще не решил.


По остальным пунктам буду фиксить. Зум по клику тоже хорошая идея

**Comment by ongots** [comment]
Дерево рулит
![2019-02-01_153515](https://user-images.githubusercontent.com/43604031/52126125-18a47a80-2637-11e9-9efc-3238ebf68143.png)

**Comment by ongots** [comment]
Функция Move file to... очень важна для меня, поэтому я набросал макет. 
![2019-02-03_054041](https://user-images.githubusercontent.com/43604031/52172358-5b20a100-2776-11e9-914c-fc644e120b8c.png)
Большую часть времени мне не нужно закрепленное меню, поэтому при нажатии M меню открывается(под курсором как контекстное меню) не закрепленным, чтобы закрепить нужно нажать замочек. При этом меню закрепляется в том месте где было открыто, т.е. его можно закрепить в любом удобном месте. 
После нажатия на минус, нажать на пункт меню и он удалится.
На последней использованной папке появляется буква М. Чтобы переместить файл в туже папку достаточно нажать М дважды.
Возможное количество папок от 1 до 50.

Можно сделать по умолчанию "folderView=LMB_DoubleClick", "moveToTrash=MiddleButton"

**Comment by ongots** [comment]
Добавить опцию "Info bar background", чтобы отключить фон.

Сделать боковую панель(дерево) выпадающей при навидении. 
В режиме папки это даст больше превью.
В режиме просмотра выпадающая панель заменит "Move to ..." для сортировки изображений.
