### ISSUE TITLE
Transparency does not persist

### ISSUE THREAD

**Issue by kamiyaa** [easymodo/qimgv#73]
Transparency fails to persist after setting it in settings, then closing qimgv and re-opening it.
On wayland on swaywm.

**Comment by easymodo** [comment]
Just tried this on sway and it worked fine. Weird.
Do other settings persist?

**Comment by kamiyaa** [comment]
I don't seem to have `Start in fullscreen` on :/

`qt-5.11.3`

**Comment by easymodo** [comment]
Do you still have this issue on sway 1.0? I can't reproduce it

**Comment by kamiyaa** [comment]
Yea, I can still reproduce it.

**Comment by easymodo** [comment]
Alright, it is indeed broken with Qt 5.11, but only when you have `Start in fullscreen` on. No issue otherwise

Qt got fullscreen on wayland with 5.12
