### ISSUE TITLE
[ENH] Folder navigation in the folder view

### ISSUE THREAD

**Issue by norcalli** [easymodo/qimgv#74]
I just came across this program a few days ago, and I've already replaced feh with this as my default image viewer, love the speed and design choices!

The only features that I found myself wanting were that I would want to be able to navigate my file system more easily (and another one that someone else already opened).

I imagined that there would be two approaches to this, which is to replace the default file picker with a more keyboard friendly one, or to leverage the custom folder viewer that is already built into the program, which is the folderView/gallery and just surface folders in there so that we can descend/ascend. The simplest implementation would be to just add a `..` and show the current folders, and maybe have an option for hiding/showing hidden folders, but that's probably not necessary.

**Comment by easymodo** [comment]
better late than never
[https://github.com/easymodo/qimgv/releases/tag/v0.9](https://github.com/easymodo/qimgv/releases/tag/v0.9)
