### ISSUE TITLE
[Question] Refreshing images

### ISSUE THREAD

**Issue by jatcwang** [easymodo/qimgv#75]
I use qimgv extensively when viewing my images while also use a RAW editing software that overwrites the JPG file. I noticed that after a while the photo is automatically updated to what has been recently written, but since it's automatic, I am having trouble figuring out whether I'm looking at what I have just processed, or the old version.

Is there a way to force a reload of the current image? Or any workaround context isn't lost (i.e. So user won't need to find the image again)

Thank you! :slightly_smiling_face:

**Comment by easymodo** [comment]
I've just added a `ReloadImage` action (F5 key), it will be in the next version. Ideally in future qimgv will watch the current folder for changes and reload automatically.

Right now as a workaround you can switch to the next 2 images and back (something like right right, left left)

**Comment by easymodo** [comment]
Or just build the `dev` branch if you have time for that stuff

**Comment by jatcwang** [comment]
Excellent tyvm! Does `ReloadImage` reload all images or just the current one?

**Comment by easymodo** [comment]
Current one
