### ISSUE TITLE
Two issues: cropping  and renaming

### ISSUE THREAD

**Issue by nick-s-b** [easymodo/qimgv#76]
Hi,

I've been using qimgv for a couple of years now and I really prefer the old way of cropping to this new one. Before, you could just drag the mouse from anywhere and create the crop region. Newer version forces you to hunt for handles in the corners of the screen (which can activate hot corners if you have those set up) and it's just generally less convenient since you have to move the mouse all across the screen. I understand why the drag handles are there but maybe the compromise would be to still allow arbitrarily drawing the crop region when the user doesn't click on the drag handles and just move the corner that's closes to the position where the user clicked? Or just let the user draw the crop region and when you detect the click that's not on the handle?

One other issue is that I find myself often renaming image files and then moving them to a permanent location. I can write a script and pop-up a rename box from a script but I have no way of letting the qimgv know that the name has changed and then you can't move it. And since qimgv doesn't monitor folders for file changes, I have to restart qimgv for it to see changes. Maybe there could be a builtin rename feature? 😄 Alternatively, maybe a way to watch folders for file changes with QFileSystemWatcher?

Thanks so much for qimgv... even after all this time I still use it daily and it's still the best!

**Comment by easymodo** [comment]
Well the file watcher is basically working, so the rename feature should be *EZ*. 

Regarding renaming AND moving: i could pimp up the Move File feature so you could do something like shift+[1,2,3...] and it will additionally prompt for a new filename.

The new cropper is simpler code-wise, also it's basically mimics gwenview's behavior. But if you think it is worse I could bring old one back.

**Comment by smaragdus** [comment]
I also prefer the old cropper. Perhaps there might be an option in settings which one to be used- the old one or the new one, I suppose that way everyone would be happy.

**Comment by nick-s-b** [comment]
@easymodo Old cropper worked like Gimp, Krita, Paint.NET, Photoshop and every other image application I remember using. Even the OS/DE-provided screenshotting of a region works this way. I don't think I've ever tried gwenview so I can't comment on how that one works. But yeah, old one was way easier to use. When I don't care about the quality, I've been using screenshotting capability of my DE to make 'cropped' versions since it's easier than the new qimgv cropper.

Yay on the rename! Can't wait!

@smaragdus Yeah, option would be nice... if some people really like the new cropper.

**Comment by blackICE19240** [comment]
Well I prefer the new crop 😅

**Comment by easymodo** [comment]
Sorry i kinda forgot about this for a while  :)  
Crop now behaves as before (unselected by default, right click clears selection)
