### ISSUE TITLE
metadata preview

### ISSUE THREAD

**Issue by alekksander** [easymodo/qimgv#77]
would it be possible to have metadata displayed on demand? is such option planned?

**Comment by easymodo** [comment]
Yes it is planned

**Comment by alekksander** [comment]
is anything going on in this regard?

**Comment by easymodo** [comment]
Yes actually. Here's what i have currently   [https://i.imgur.com/t6KhuVq.jpg](https://i.imgur.com/t6KhuVq.jpg)

**Comment by alekksander** [comment]
nice. do You plan to make it configurable? — like expanding from auto hide and such. also, is new interface coming?

**Comment by easymodo** [comment]
it's an overlay like a copy dialog. toggle show/hide by pressing I

now really a new ui, but some theme tweaks to make it look cleaner

**Comment by alekksander** [comment]
do You perhaps plan to release soon?

**Comment by easymodo** [comment]
maybe this weekend.  still need to finish some stuff for windows build

**Comment by alekksander** [comment]
thank You
