### ISSUE TITLE
[Feature Request] Get absolute path of current file (or copy image to clipboard)

### ISSUE THREAD

**Issue by jatcwang** [easymodo/qimgv#78]
I often find myself going through my photos using qimgv and searching for a photo to upload. Currently, after finding the image, I need to find it again using the file picker or get the absolute path through file browser.

I think the ability to copy the absolute path of the current image will really help. Or copy the image into clipboard since many app (e.g. Signal, whatsapp) can handle pasting image from clipboard too.

Happy to take a stab at it! Thanks

**Comment by easymodo** [comment]
Done (will be available in the next release). Defaults are `ctrl+c` to copy file, `shift+ctrl+c` to copy path.
