### ISSUE TITLE
[Feature request] "Show image info" in non-fullscreen

### ISSUE THREAD

**Issue by Kattus** [easymodo/qimgv#82]
As the title describes, I'd like to be able to enable "Show Image Info" when not in fullscreen mode, possibly with a keybind for toggling but perhaps that's for another ticket.

As a previously Honeyview user, this is the closest thing on Linux and I love it. <3

To clarify what option I'm talking about:
![pref window](https://i.imgur.com/Du8avYp.png)

**Comment by easymodo** [comment]
[Quick mockup](https://files.catbox.moe/v3hxga.png)

It'll go under the image (not overlayed like fullscreen one)

**Comment by Kattus** [comment]
That looks perfect, thank you for you quick response!
