### ISSUE TITLE
qimgv icon is wrong on KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [easymodo/qimgv#83]
Hi

I have qimgv 0.7.3 installed on Arch Linux.
As we can see in the screenshot below, its icon is wrong when running on KDE Plasma Wayland session. Maybe the following link is helpful.
https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Application_Icon

![qimgv](https://user-images.githubusercontent.com/15967631/55336228-fbdbc600-5472-11e9-84f2-2a76d9543a98.png)

**Comment by easymodo** [comment]
done, fix will come with v0.8
