### ISSUE TITLE
Show video controls checkbox bug

### ISSUE THREAD

**Issue by Yotimoto** [easymodo/qimgv#86]
The Show video controls checkbox doesn't seem to do anything right now, and doesn't save its state after you close the window.
Using v0.7.3 video on windows.

As a side note, it would be great if there was a toggle to mute/unmute videos with sound in the video controls. Being able to toggle between having a video scale to fit the window and/or zooming would also be great but I understand if that might be pushing the scope of this project.

**Comment by easymodo** [comment]
I'll probably remove the option altogether, as the panel already autohides.. Along with some tweaks to autohide behavior to make it less distracting

"Expand smaller images" option works on videos. 
Next version will have toggle shortcuts for some options where it makes sense
