### ISSUE TITLE
[Bug] Deleting .gifs or other animated media has no effect.

### ISSUE THREAD

**Issue by Greysion** [easymodo/qimgv#88]
This feels fairly broad, however, I haven't found a circumstance where it hasn't happened.

• If you attempt to delete a .gif or .webm, it doesn't have any effect on the actual file itself. It remains in the folder qimgv is viewing.

• If you attempt to move a .gif or .webm, it instead duplicates the file to the new location.

**Comment by easymodo** [comment]
Confirmed, thanks for reporting.
