### ISSUE TITLE
Thumbnail panel stops generating thumbnails

### ISSUE THREAD

**Issue by denzerdhard** [easymodo/qimgv#93]
If you click on scrollbar to jump to specific location thumbnails stop generating until manually scrolled or hiding/unhiding panel.
Another thing that i highly miss is ability to change sorting at runtime.

**Comment by denzerdhard** [comment]
Still not generating. Then i middle click on scrollbar in gnome or left click in kde qdebug says action == 7.

**Comment by easymodo** [comment]
Should be working now. I also removed load delay so it should feel a bit better
