### ISSUE TITLE
Lockup on hiding thumbnail panel

### ISSUE THREAD

**Issue by denzerdhard** [easymodo/qimgv#94]
I noticed strange thing, then i open large image collection (around 50000), it opens pretty quick and you can navigate around fine and thumbnail panel opens quick too, but then as soon as mouse leaves thumbnail panel program locks up and uses 100% of one cpu core for a couple of minutes and then thing becomes normal again.

**Comment by easymodo** [comment]
Tested on ~50k files, seems usable now. I'll also look into dolphin's source later, whatever they do for directory views works beautifully

**Comment by denzerdhard** [comment]
Wow, thank you. Its super fast now.
