### ISSUE TITLE
webp jaggedness

### ISSUE THREAD

**Issue by denzerdhard** [easymodo/qimgv#96]
Feels like billinear scaling doesn't apply to webp.
jpg:
![1](https://user-images.githubusercontent.com/3885773/59354520-ba06b000-8d3e-11e9-925c-a49e16878349.png)
webp:
![2](https://user-images.githubusercontent.com/3885773/59354542-c4c14500-8d3e-11e9-8656-db86a507235b.png)

**Comment by easymodo** [comment]
that's because currently it treats all webp as "animated"

you can enable option to smooth them in `settings > scaling`

**Comment by easymodo** [comment]
fixed
