### ISSUE TITLE
Shuffle (and possible slideshow)

### ISSUE THREAD

**Issue by SaltBadGuy** [easymodo/qimgv#97]
it'd be nice to browse through images randomly rather than any strict order. Slideshow might be nice as well.

**Comment by AeliusSaionji** [comment]
Seconded. That's what I need before I can uninstall the other viewer I use.

Definitely shuffle

**Comment by Hrxn** [comment]
https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle

**Comment by AeliusSaionji** [comment]
> Definitely shuffle

Oops, I meant definitely shuffle and slideshow as well!

**Comment by easymodo** [comment]
btw you can already use `toggleShuffle` (on 0.8.3+), there's just no default shortcut

**Comment by Zivoz** [comment]
Can you make the shuffle not show duplicates in the same queue? Ex. 20 images, queue of 20, random order, reshuffle at end. Currently it seems it can show the same image in close succession.

**Comment by AeliusSaionji** [comment]
That's "true random" for ya.

**Comment by easymodo** [comment]
ok slideshow done on `dev` branch

**Comment by easymodo** [comment]
[https://github.com/easymodo/qimgv/releases/tag/v0.9](https://github.com/easymodo/qimgv/releases/tag/v0.9)
