### ISSUE TITLE
Linux Install: "fatal error: QVersionNumber: No such file or directory"

### ISSUE THREAD

**Issue by RC-3** [easymodo/qimgv#98]
Running GalliumOS on a Dell Chromebook 13.
(Linux Rookie)

I followed the instructions but can't get it installed.
Everything was fine until this:

```
bob@chrx:~/qimgv/build$ cmake -DVIDEO_SUPPORT=ON -DCMAKE_INSTALL_PREFIX=/usr/ -DCMAKE_BINARY_DIR=${DIR}/ .. && make -j4
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/bob/qimgv/build
Scanning dependencies of target qimgv_automoc
[  1%] Automatic moc and uic for target qimgv
Generating ui_contextmenu.h
Generating ui_pathselectorwidget.h
Generating ui_resizedialog.h
Generating ui_scripteditordialog.h
Generating ui_settingsdialog.h
Generating ui_shortcutcreatordialog.h
Generating ui_folderview.h
Generating ui_changelogwindow.h
Generating ui_copyoverlay.h
Generating ui_floatingmessage.h
Generating ui_saveconfirmoverlay.h
Generating ui_videocontrols.h
Generating ui_croppanel.h
Generating ui_sidepanel.h
Generating moc_actionmanager.cpp
Generating moc_thumbnailcache.cpp
Generating moc_directorymanager.cpp
Generating moc_directorywatcher.cpp
Generating moc_directorywatcher_p.cpp
Generating moc_linuxwatcher.cpp
Generating moc_linuxwatcher_p.cpp
Generating moc_linuxworker.cpp
Generating moc_watcherworker.cpp
Generating moc_loader.cpp
Generating moc_loaderrunnable.cpp
Generating moc_scaler.cpp
Generating moc_scalerrunnable.cpp
Generating moc_scriptmanager.cpp
Generating moc_thumbnailer.cpp
Generating moc_thumbnailerrunnable.cpp
Generating moc_core.cpp
Generating moc_centralwidget.cpp
Generating moc_contextmenu.cpp
Generating moc_clickablelabel.cpp
Generating moc_clickablewidget.cpp
Generating moc_contextmenuitem.cpp
Generating moc_floatingwidget.cpp
Generating moc_keysequenceedit.cpp
Generating moc_overlaycontainerwidget.cpp
Generating moc_overlaywidget.cpp
Generating moc_pathselectorwidget.cpp
Generating moc_sidepanelwidget.cpp
Generating moc_slidehpanel.cpp
Generating moc_slidepanel.cpp
Generating moc_slidevpanel.cpp
Generating moc_spinboxinputfix.cpp
Generating moc_thumbnailview.cpp
Generating moc_thumbnailwidget.cpp
Generating moc_videoslider.cpp
Generating moc_resizedialog.cpp
Generating moc_scripteditordialog.cpp
Generating moc_settingsdialog.cpp
Generating moc_shortcutcreatordialog.cpp
Generating moc_foldergridview.cpp
Generating moc_folderview.cpp
Generating moc_mainwindow.cpp
Generating moc_changelogwindow.cpp
Generating moc_controlsoverlay.cpp
Generating moc_copyoverlay.cpp
Generating moc_cropoverlay.cpp
Generating moc_floatingmessage.cpp
Generating moc_infooverlay.cpp
Generating moc_mapoverlay.cpp
Generating moc_saveconfirmoverlay.cpp
Generating moc_videocontrols.cpp
Generating moc_croppanel.cpp
Generating moc_mainpanel.cpp
Generating moc_thumbnailstrip.cpp
Generating moc_sidepanel.cpp
Generating moc_imageviewer.cpp
Generating moc_mpvwidget.cpp
Generating moc_videoplayermpv.cpp
Generating moc_videoplayer.cpp
Generating moc_viewerwidget.cpp
Generating moc_settings.cpp
Generating moc_helprunner.cpp
[  1%] Built target qimgv_automoc
[  2%] Generating qrc_resources.cpp
Scanning dependencies of target qimgv
[  3%] Building CXX object CMakeFiles/qimgv.dir/main.cpp.o
[  4%] Building CXX object CMakeFiles/qimgv.dir/core.cpp.o
[  5%] Building CXX object CMakeFiles/qimgv.dir/settings.cpp.o
[  6%] Building CXX object CMakeFiles/qimgv.dir/appversion.cpp.o
In file included from /home/bob/qimgv/appversion.cpp:1:0:
/home/bob/qimgv/appversion.h:4:26: fatal error: QVersionNumber: No such file or directory
compilation terminated.
CMakeFiles/qimgv.dir/build.make:207: recipe for target 'CMakeFiles/qimgv.dir/appversion.cpp.o' failed
make[2]: *** [CMakeFiles/qimgv.dir/appversion.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/bob/qimgv/core.h:9:0,
                 from /home/bob/qimgv/core.cpp:8:
/home/bob/qimgv/appversion.h:4:26: fatal error: QVersionNumber: No such file or directory
compilation terminated.
CMakeFiles/qimgv.dir/build.make:231: recipe for target 'CMakeFiles/qimgv.dir/core.cpp.o' failed
make[2]: *** [CMakeFiles/qimgv.dir/core.cpp.o] Error 1
In file included from /home/bob/qimgv/main.cpp:2:0:
/home/bob/qimgv/appversion.h:4:26: fatal error: QVersionNumber: No such file or directory
compilation terminated.
CMakeFiles/qimgv.dir/build.make:159: recipe for target 'CMakeFiles/qimgv.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/qimgv.dir/main.cpp.o] Error 1
In file included from /home/bob/qimgv/settings.cpp:1:0:
/home/bob/qimgv/settings.h:15:26: fatal error: QVersionNumber: No such file or directory
 #include <QVersionNumber>
                          ^
compilation terminated.
CMakeFiles/qimgv.dir/build.make:183: recipe for target 'CMakeFiles/qimgv.dir/settings.cpp.o' failed
make[2]: *** [CMakeFiles/qimgv.dir/settings.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/qimgv.dir/all' failed
make[1]: *** [CMakeFiles/qimgv.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
bob@chrx:~/qimgv/build$
``` 

Any suggestions are appreciated. :)
Thanks!

**Comment by easymodo** [comment]
The only thing that comes to mind is that you have an old Qt version. qimgv requires at least 5.9

**Comment by RC-3** [comment]
Looks like I've got qt5 installed, v6.1. 
Here's the output of sudo apt list --installed | grep qt5
`
libqt5concurrent5/xenial-updates,xenial-security,now 5.5.1+dfsg-16ubuntu7.6 amd64 [installed,automatic]
libqt5core5a/xenial-updates,xenial-security,now 5.5.1+dfsg-16ubuntu7.6 amd64 [installed,automatic]
libqt5dbus5/xenial-updates,xenial-security,now 5.5.1+dfsg-16ubuntu7.6 amd64 [installed,automatic]
libqt5gui5/xenial-updates,xenial-security,now 5.5.1+dfsg-16ubuntu7.6 amd64 [installed,automatic]
libqt5network5/xenial-updates,xenial-security,now 5.5.1+dfsg-16ubuntu7.6 amd64 [installed,automatic]
libqt5opengl5/xenial-updates,xenial-security,now 5.5.1+dfsg-16ubuntu7.6 amd64 [installed,automatic]
libqt5opengl5-dev/xenial-updates,xenial-security,now 5.5.1+dfsg-16ubuntu7.6 amd64 [installed,automatic]
libqt5printsupport5/xenial-updates,xenial-security,now 5.5.1+dfsg-16ubuntu7.6 amd64 [installed,automatic]
libqt5qml5/xenial,now 5.5.1-2ubuntu6 amd64 [installed,automatic]
libqt5quick5/xenial,now 5.5.1-2ubuntu6 amd64 [installed,automatic]
libqt5sql5/xenial-updates,xenial-security,now 5.5.1+dfsg-16ubuntu7.6 amd64 [installed,automatic]
libqt5sql5-sqlite/xenial-updates,xenial-security,now 5.5.1+dfsg-16ubuntu7.6 amd64 [installed,automatic]
libqt5svg5/xenial,now 5.5.1-2build1 amd64 [installed,automatic]
libqt5test5/xenial-updates,xenial-security,now 5.5.1+dfsg-16ubuntu7.6 amd64 [installed,automatic]
libqt5webkit5/xenial,now 5.5.1+dfsg-2ubuntu1 amd64 [installed,automatic]
libqt5widgets5/xenial-updates,xenial-security,now 5.5.1+dfsg-16ubuntu7.6 amd64 [installed,automatic]
libqt5x11extras5/xenial,now 5.5.1-3build1 amd64 [installed,automatic]
libqt5xml5/xenial-updates,xenial-security,now 5.5.1+dfsg-16ubuntu7.6 amd64 [installed,automatic]
qt5-default/xenial-updates,xenial-security,now 5.5.1+dfsg-16ubuntu7.6 amd64 [installed]
qt5-qmake/xenial-updates,xenial-security,now 5.5.1+dfsg-16ubuntu7.6 amd64 [installed,automatic]`

**Comment by RC-3** [comment]
Thank you so much for replying!
And you were right, my qt5 and libmpv versions weren't high enough. My OS doesn't offer the latest versions by default. I had to update them manually.

I'm still getting the same error after I updated the prereqs.

_Troubleshooting notes for future Linux rookies:
Check qt5 version:
     sudo apt list --installed | grep qt5
Installed Qt 5.11.2 via https://askubuntu.com/questions/1062046/how-to-update-qt-from-5-5-1-to-5-9-5-on-ubuntu-16-04
Check libmpv version:
     sudo apt list --installed | grep libmpv
Installed libmpv 0.22 via https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests_

I checked with qmake -v
```
qmake -v
QMake version 3.1
Using Qt version 5.12.4 in /opt/Qt/5.12.4/gcc_64/lib
```
I reset the install after every attempt. 
cd ~ && rm qimgv -f -r
then I go back and repeat Step 2 of the instructions.

I'm getting the same QVersionNumber error as above; in main.cpp, core.cpp, and settings.cpp
```
In file included from /home/mal/qimgv/settings.cpp:1:0:
/home/bob/qimgv/settings.h:15:26: fatal error: QVersionNumber: No such file or directory
 #include <QVersionNumber>
```
I opened the qimgv/appversion.h file to see what it says.
```
#ifndef APPVERSION_H
#define APPVERSION_H

#include <QVersionNumber>

extern QVersionNumber appVersion;

#endif // APPVERSION_H
``` 

I'm not sure what to try next. Any further suggestions?

**Comment by easymodo** [comment]
when you do the `cmake` part, pass additional parameter so it uses qt5.11 like this

```
cmake -DCMAKE_PREFIX_PATH=/opt/qt511/ -DVIDEO_SUPPORT=ON -DCMAKE_INSTALL_PREFIX=/usr/ -DCMAKE_BINARY_DIR=${DIR}/ .. && make -j4
```

[it works](https://i.imgur.com/dNIn5Ow.jpg)

There's an issue of missing icon on taskbar idk what's up with that

BTW you can avoid all this headaches by just using newer galliumos 3.0 it was released a few days ago. It should have up-to-date packages (based on 18.04)
