### ISSUE TITLE
Menu key support

### ISSUE THREAD

**Issue by linxon** [easymodo/qimgv#99]
Please add a Menu key support for context menu

![MenuKey](https://user-images.githubusercontent.com/8144644/60610251-12741f00-9dcc-11e9-8763-e70177d040b1.jpg)
![Screenshot_2019-07-03_19-54-54](https://user-images.githubusercontent.com/8144644/60610503-a514be00-9dcc-11e9-9b7c-680c38b6d179.png)

**Comment by easymodo** [comment]
done. better keyboard navigation is coming later as well
